<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="keywords" content="Ottawa watercolour oil artist paint painting art Canada landscape floral abstract for sale local Quebec Gatineau Outaouais affordable buy purchase order cheap gift present Galerie Old Chelsea gallery cadeau peinture artiste huile aquarelle fleurs abstrait dessin paysage abordable commander acheter Wakefield">
    <meta name="description" content="Lina Yachnin is a Canadian oil & watercolour artist who paints landscapes, floral arrangements, and abstract images.">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=0">
    <link rel="shortcut icon" type="image/png" href="favicon.ico" />
    
	<link rel="stylesheet" type="text/css" href="./css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="style.css"><link rel='stylesheet' href='./css/font-awesome.min.css'/><link href='http://fonts.googleapis.com/css?family=helvetica&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
    
	<script src="./js/jquery-2.1.0.min.js"></script>
	<script src="./js/bootstrap.min.js"></script>
	<script src="./js/blocs.min.js"></script>
	<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-88189548-1', 'auto');
  ga('send', 'pageview');

</script>
    <title>Lina Yachnin – About</title>

    <meta property="og:image" content="http://www.linayachnin.com/img/lina_yachnin_facebook_profile.jpg"/>
    <meta property="og:description" content="Lina Yachnin is a Canadian oil & watercolour artist who paints landscapes, floral arrangements, and abstract images."/>

<meta property="og:url" content="http://www.linayachin.com"/>

<meta property="og:title" content="Lina Yachnin — Canadian Oil & Watercolour Artist"/>

</head>
<body>
<!-- Main container -->
<div class="page-container">
    
<!-- bloc-navbar-mobile -->
<div class="bloc hidden-sm hidden-lg hidden-md bgc-gray-x11-gray l-bloc" id="bloc-navbar-mobile">
	<div class="container">
		<nav class="navbar row">
			<div class="navbar-header">
				<a href="http://www.facebook.com/linayachninart/" class="icon-padding" target="_blank"><span class="fa fa-facebook icon-md pull-left"></span></a><a href="https://www.linkedin.com/in/lina-yachnin-54a9a28a" target="_blank"><span class="fa fa-linkedin icon-md pull-left"></span></a>
				<button id="nav-toggle" type="button" class="ui-navbar-toggle navbar-toggle" data-toggle="collapse" data-target=".navbar-1">
					<span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
				</button>
			</div>
			<div class="navbar-collapse navbar-1 collapse">
				<ul class="site-navigation nav navbar-nav list-dimensions">
					<li>
						<a href="index">Home</a>
					</li>
					<li>
						<a href="exhibitions">Exhibitions</a>
					</li>
					<li>
						<a href="about">About</a>
					</li>
					<li>
						<a href="available_works">Available Works</a>
					</li>
					<li>
						<a href="florals">Florals</a>
					</li>
					<li>
						<a href="landscapes">Landscapes</a>
					</li>
					<li>
						<a href="abstracts">Abstracts</a>
					</li>
					<li>
						<a href="urbanscapes">Urbanscapes</a>
					</li>
					<li>
						<a href="contact">Contact</a>
					</li>
				</ul>
			</div>
		</nav>
	</div>
</div>
<!-- bloc-navbar-mobile END -->

<!-- bloc-navbar-about-desktop -->
<div class="bloc hidden-xs hidden-sm bgc-white l-bloc pad-top-nav" id="bloc-navbar-about-desktop">
	<div class="container bloc-sm">
		<div class="row">
			<div class="col-sm-4">
				<a href="index"><img src="img/short-sig.jpg" class="img-responsive" width="254" alt="Lina Yachnin"/></a>
			</div>
			<div class="col-sm-8">
				<ul class="list-unstyled list-horizontal-layout list-container">
					<li>
						<a href="index">Home</a>
					</li>
					<li>
						<a href="exhibitions">Exhibitions</a>
					</li>
					<li>
						<a href="available_works">Available Works</a>
					</li>
					<li>
						<a href="florals">Florals</a>
					</li>
					<li>
						<a href="landscapes">Landscapes</a>
					</li>
					<li>
						<a href="abstracts">Abstracts</a>
					</li>
					<li>
						<a href="urbanscapes">Urbanscapes</a>
					</li>
					<li>
						<a href="contact">Contact</a>
					</li>
				</ul>
			</div>
		</div>
	</div>
</div>
<!-- bloc-navbar-about-desktop END -->

<!-- bloc-navbar-about-tablet -->
<div class="bloc hidden-xs hidden-lg hidden-md bgc-white l-bloc" id="bloc-navbar-about-tablet">
	<div class="container bloc-sm">
		<div class="row">
			<div class="col-sm-6">
				<a href="index"><img src="img/short-sig.jpg" class="img-responsive center-block" width="261" alt="Lina Yachnin"/></a>
			</div>
			<div class="col-sm-6">
				<ul class="list-unstyled list-horizontal-layout">
					<li>
						<a href="index">Home</a>
					</li>
					<li>
						<a href="exhibitions">Exhibitions</a>
					</li>
					<li>
						<a href="available_works">Available Works</a>
					</li>
					<li>
						<a href="florals">Florals</a>
					</li>
					<li>
						<a href="landscapes">Landscapes</a>
					</li>
					<li>
						<a href="abstracts">Abstracts</a>
					</li>
					<li>
						<a href="urbanscapes">Urbanscapes</a>
					</li>
					<li>
						<a href="contact">Contact</a>
					</li>
				</ul>
			</div>
		</div>
	</div>
</div>
<!-- bloc-navbar-about-tablet END -->

<!-- bloc-about-banner -->
<div class="bloc bg-Trilliums-bckgrnd bgc-white-2 l-bloc b-parallax bg-r-edge banner" id="bloc-about-banner">
	<div class="container bloc-lg">
		<div class="row">
			<div class="col-sm-12">
				<h1 class="mg-md mm-links">
					<strong>Artist&rsquo;s Statement</strong>
				</h1>
			</div>
		</div>
	</div>
</div>
<!-- bloc-about-banner END -->

<!-- bloc-about-statement -->
<div class="bloc bgc-white-2 l-bloc" id="bloc-about-statement">
	<div class="container bloc-lg">
		<div class="row">
			<div class="col-sm-12">
				<p class="text-center ">
					My objective is to draw the viewer&rsquo;s attention to the components of an image that I find inspirational. Composition functions as the basis of my work. A semi-abstract approach is used to further simplify and strengthen the surrounding landscape.<br /><br />I enjoy using oils and watercolour as both have an interactive quality that I find very appealing. Through the use of vibrant colour, as well as my love for the outdoors, I strive to engage the viewer on an emotional level.<br />
				</p>
			</div>
		</div>
	</div>
</div>
<!-- bloc-about-statement-desktop END -->

<!-- bloc-about-cv -->
<div class="bloc bgc-white-2 bg-Sundown d-bloc bg-l-edge b-parallax banner" id="bloc-about-cv">
	<div class="container bloc-lg">
		<div class="row">
			<div class="col-sm-12">
				<h1 class="mg-md mm-links tc-white-2">
					<strong>Curriculum Vitae</strong>
				</h1>
			</div>
		</div>
	</div>
</div>
<!-- bloc-about-cv END -->

<!-- Bloc Group -->
<div class='bloc-group'>

<!-- bloc-about-soloshows -->
<div class="bloc bloc-tile-2 bgc-white-2 l-bloc" id="bloc-about-soloshows">
	<div class="container bloc-sm">
		<div class="row">
			<div class="col-sm-12">
				<h2 class="mg-md text-left">
					Solo Shows
				</h2>
				<blockquote>
					<p class="text-left ">
						October 2017 — "<i>Passerelle</i>”, Galerie Old Chelsea
					</p>
				</blockquote>
				<blockquote>
					<p class="text-left ">
						October 2015 — “<i>Reflections</i>”, Galerie Old Chelsea
					</p>
				</blockquote>
				<blockquote>
					<p class="text-left ">
						October 2013 — “<i>Abstract To Realism</i>”, Galerie Old Chelsea
					</p>
				</blockquote>
				<blockquote>
					<p class="text-left ">
						August 2010 — “<i>Stories in Colour</i>”, Galerie Old Chelsea
					</p>
				</blockquote>
				<blockquote>
					<p class="text-left ">
						May 2008 — "<i>Off the Beaten Track</i>”, Galerie Old Chelsea
					</p>
				</blockquote>
			</div>
		</div>
	</div>
</div>
<!-- bloc-about-soloshows END -->

<!-- bloc-about-groupshows -->
<div class="bloc bloc-tile-2 bgc-white-2 l-bloc" id="bloc-about-groupshows">
	<div class="container bloc-sm">
		<div class="row">
			<div class="col-sm-12">
				<h2 class="mg-md text-left ">
					Group Shows
				</h2>
				<blockquote>
					<p class="text-left ">
						2002 to 2015 — Juried shows, Ottawa Watercolour Society
					</p>
				</blockquote>
				<blockquote>
					<p class="text-left ">
						August 2010 — “Homage to the Abstract”, Cube Gallery
					</p>
				</blockquote>
				<blockquote>
					<p class="text-left ">
						2010 — Smalls Show, Cube Gallery
					</p>
				</blockquote>
				<blockquote>
					<p class="text-left ">
						2008 — Smalls Show, Cube Gallery
					</p>
				</blockquote>
			</div>
		</div>
	</div>
</div>
<!-- bloc-about-groupshows END -->
</div>
<!-- Bloc Group END -->

<!-- bloc-about-gallerybanner -->
<div class="bloc bg-Autumn-Wonder bgc-white-2 l-bloc bg-l-edge b-parallax banner" id="bloc-about-gallerybanner">
	<div class="container bloc-lg">
		<div class="row">
			<div class="col-sm-12">
				<h1 class="mg-md mm-links tc-white-2">
					<strong>Galerie Old Chelsea</strong>
				</h1>
			</div>
		</div>
	</div>
</div>
<!-- bloc-about-gallerybanner END -->

<!-- bloc-about-location -->
<div class="bloc bgc-white-2 l-bloc" id="bloc-about-location">
	<div class="container bloc-md">
		<div class="row">
			<div class="col-sm-12">
				<p class="text-center ">
					If you&rsquo;re interested in one of my pieces, you can contact me directly or visit me at the Galerie Old Chelsea. The gallery is located above Les Fougères Restaurant in Old Chelsea.
				</p>
			</div>
		</div>
		<div class="row voffset">
			<div class="col-sm-6">
				<a href="http://lesfougeres.com" target="_blank"><img src="img/logo-213x162.png" class="img-responsive center-block" alt="Les Fougères Restaurant" /></a>
			</div>
			<div class="col-sm-6">
				<a href="http://galerieoldchelsea.ca" target="_blank"><img src="img/24481.jpg" class="img-responsive center-block" alt="Galerie Old Chelsea"/></a>
			</div>
		</div>
	</div>
</div>
<!-- bloc-about-location END -->

<!-- Footer - bloc-social-desktop -->
<div class="bloc hidden-xs hidden-sm bgc-white l-bloc" id="bloc-social-desktop">
	<div class="container bloc-md">
		<div class="row padding-footer">
			<div class="col-sm-3 col-sm-offset-3">
				<div class="text-center">
					<a href="index"></a>
					<div class="text-center">
						<a href="index"></a><a href="http://facebook.com" target="_blank"></a>
						<div class="text-center pull-left">
							<a href="http://facebook.com" target="_blank"></a><a href="http://www.facebook.com/linayachninart/" target="_blank"><span class="fa fa-facebook icon-lg icon-dark-lava"></span></a>
						</div>
					</div>
				</div>
			</div>
			<div class="col-sm-3">
				<div class="text-center">
					<a href="index"></a>
					<div class="text-center">
						<a href="index"></a><a href="https://www.linkedin.com/in/lina-yachnin-54a9a28a" target="_blank"><span class="fa fa-linkedin icon-lg pull-left icon-dark-lava"></span></a>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- Footer - bloc-social-desktop END -->

<!-- Footer - bloc-social-tablet -->
<div class="bloc hidden-xs hidden-lg hidden-md bgc-white l-bloc" id="bloc-social-tablet">
	<div class="container bloc-md">
		<div class="row footer-tablet-padding">
			<div class="col-sm-3 col-sm-offset-3">
				<div class="text-center">
					<a href="index"></a>
					<div class="text-center">
						<a href="index"></a><a href="http://facebook.com" target="_blank"></a>
						<div class="text-center pull-left">
							<a href="http://facebook.com" target="_blank"></a><a href="http://www.facebook.com/linayachninart/" target="_blank"><span class="fa fa-facebook icon-lg icon-dark-lava"></span></a>
						</div>
					</div>
				</div>
			</div>
			<div class="col-sm-3">
				<div class="text-center">
					<a href="index"></a>
					<div class="text-center">
						<a href="index"></a><a href="https://www.linkedin.com/in/lina-yachnin-54a9a28a" target="_blank"><span class="fa fa-linkedin icon-dark-lava icon-lg pull-left"></span></a>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- Footer - bloc-social-tablet END -->
</div>
<!-- Main container END -->
    

</body>
    
<!-- Google Analytics -->
 
<!-- Google Analytics END -->

</html>
