<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
	<title>Lina Yachnin – About</title>
	<?php include 'source/meta_header.php';?>
	<meta property="og:title" content="Lina Yachnin — Canadian Oil & Watercolour Artist">
</head>
<body>
<!-- Main container -->
<div class="page-container">

<?php include 'source/navbar.php';?>

<!-- bloc-about-banner -->
<div class="bloc bg-Trilliums-bckgrnd bgc-main-bg l-bloc b-parallax bg-r-edge banner" id="bloc-about-banner">
	<div class="container bloc-lg">
		<div class="row">
			<div class="col-sm-12">
				<h1 class="mg-md over-image-title-text">
					<strong>Artist&rsquo;s Statement</strong>
				</h1>
			</div>
		</div>
	</div>
</div>
<!-- bloc-about-banner END -->

<!-- bloc-about-statement -->
<div class="bloc bgc-main-bg l-bloc" id="bloc-about-statement">
	<div class="container bloc-lg">
		<div class="row">
			<div class="col-sm-12">
				<h6 class="text-center ">
					My objective is to draw the viewer&rsquo;s attention to the components of an image that I find inspirational. Composition functions as the basis of my work. A semi-abstract approach is used to further simplify and strengthen the surrounding landscape.<br><br>I enjoy using oils and watercolour as both have an interactive quality that I find very appealing. Through the use of vibrant colour, as well as my love for the outdoors, I strive to engage the viewer on an emotional level.<br>
</h6>
			</div>
		</div>
	</div>
</div>
<!-- bloc-about-statement-desktop END -->

<!-- bloc-about-cv -->
<div class="bloc bgc-main-bg bg-Sundown l-bloc bg-l-edge b-parallax banner" id="bloc-about-cv">
	<div class="container bloc-lg">
		<div class="row">
			<div class="col-sm-12">
				<h1 class="mg-md over-image-title-text tc-white">
					<strong>Curriculum Vitae</strong>
				</h1>
			</div>
		</div>
	</div>
</div>
<!-- bloc-about-cv END -->

<!-- Bloc Group -->
<div class='bloc-group'>

<!-- bloc-about-soloshows -->
<div class="bloc bloc-tile-2 bgc-main-bg l-bloc" id="bloc-about-soloshows">
	<div class="container bloc-sm">
		<div class="row">
			<div class="col-sm-12 list">
				<h2 class="mg-md text-left">
					Solo Shows
				</h2>
				<blockquote>
					<p class="text-left ">
						October 2022 — "<i>Des gens et des lieux</i>”, Galerie Old Chelsea
					</p>
				</blockquote>
				<blockquote>
					<p class="text-left ">
						October 2020 — "<i>Through the Trees</i>”, Galerie Old Chelsea
					</p>
				</blockquote>
				<blockquote>
					<p class="text-left ">
						June-July 2018 — Sienna Gallery
					</p>
				</blockquote>
				<blockquote>
					<p class="text-left ">
						October 2017 — "<i>Passerelle</i>”, Galerie Old Chelsea
					</p>
				</blockquote>
				<blockquote>
					<p class="text-left ">
						October 2015 — “<i>Reflections</i>”, Galerie Old Chelsea
					</p>
				</blockquote>
				<blockquote>
					<p class="text-left ">
						October 2013 — “<i>Abstract To Realism</i>”, Galerie Old Chelsea
					</p>
				</blockquote>
				<blockquote>
					<p class="text-left ">
						August 2010 — “<i>Stories in Colour</i>”, Galerie Old Chelsea
					</p>
				</blockquote>
				<blockquote>
					<p class="text-left ">
						May 2008 — "<i>Off the Beaten Track</i>”, Galerie Old Chelsea
					</p>
				</blockquote>
			</div>
		</div>
	</div>
</div>
<!-- bloc-about-soloshows END -->

<!-- bloc-about-groupshows -->
<div class="bloc bloc-tile-2 bgc-main-bg l-bloc" id="bloc-about-groupshows">
	<div class="container bloc-sm">
		<div class="row">
			<div class="col-sm-12 list">
				<h2 class="mg-md text-left ">
					Group Shows
				</h2>
				<blockquote>
					<p class="text-left ">
						2002 to 2015 — Juried shows, Ottawa Watercolour Society
					</p>
				</blockquote>
				<blockquote>
					<p class="text-left ">
						August 2010 — “Homage to the Abstract”, Cube Gallery
					</p>
				</blockquote>
				<blockquote>
					<p class="text-left ">
						2010 — Smalls Show, Cube Gallery
					</p>
				</blockquote>
				<blockquote>
					<p class="text-left ">
						2008 — Smalls Show, Cube Gallery
					</p>
				</blockquote>
			</div>
		</div>
	</div>
</div>
<!-- bloc-about-groupshows END -->
</div>
<!-- Bloc Group END -->

<!-- bloc-about-gallerybanner -->
<div class="bloc bg-Autumn-Wonder bgc-main-bg l-bloc bg-l-edge b-parallax banner" id="bloc-about-gallerybanner">
	<div class="container bloc-lg">
		<div class="row">
			<div class="col-sm-12">
				<h1 class="mg-md over-image-title-text tc-white">
					<strong>Galerie Old Chelsea</strong>
				</h1>
			</div>
		</div>
	</div>
</div>
<!-- bloc-about-gallerybanner END -->

<!-- bloc-about-location -->
<div class="bloc bgc-main-bg l-bloc" id="bloc-about-location">
	<div class="container bloc-md">
		<div class="row">
			<div class="col-sm-12">
				<h6 class="text-center ">
					If you&rsquo;re interested in one of my pieces, you can contact me directly or visit me at the Galerie Old Chelsea. The gallery is located above Les Fougères Restaurant in Old Chelsea.
				</h6>
			</div>
		</div>
		<div class="row voffset">
			<div class="col-sm-6">
				<a href="http://lesfougeres.com" target="_blank"><img src="img/logo-213x162.png" class="img-responsive center-block" alt="Les Fougères Restaurant"></a>
			</div>
			<div class="col-sm-6">
				<a href="http://galerieoldchelsea.ca" target="_blank"><img src="img/24481.jpg" class="img-responsive center-block" alt="Galerie Old Chelsea"></a>
			</div>
		</div>
	</div>
</div>
<!-- bloc-about-location END -->

<?php include 'source/social_footer.php';?>

</div>
<!-- Main container END -->

<?php include 'source/scripts_footer.php';?>
</body>

<!-- Google Analytics -->

<!-- Google Analytics END -->

</html>
