<!doctype html>
<html>
<head><meta http-equiv="Content-Type" content="text/html; charset=utf-8"><meta name="keywords" content="Ottawa watercolour oil artist paint painting art Canada landscape floral abstract for sale local Quebec Gatineau Outaouais affordable buy purchase order cheap gift present Galerie Old Chelsea gallery cadeau peinture artiste huile aquarelle fleurs abstrait dessin paysage abordable commander acheter Wakefield"><meta name="description" content="Lina Yachnin is a Canadian oil & watercolour artist who paints landscapes, floral arrangements, and abstract images."><meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=0">
	<link href="favicon.ico" rel="shortcut icon" type="image/png" />
	<link href="./css/bootstrap.min.css" rel="stylesheet" type="text/css" />
	<link href="style.css" rel="stylesheet" type="text/css" />
	<link href="./css/font-awesome.min.css" rel="stylesheet" />
	<link href="http://fonts.googleapis.com/css?family=helvetica&amp;subset=latin,latin-ext" rel="stylesheet" type="text/css" /><script src="./js/jquery-2.1.0.min.js"></script><script src="./js/bootstrap.min.js"></script><script src="./js/blocs.min.js"></script>
	<title>Lina Yachnin &ndash; Abstracts</title>
	<meta property="og:image" content="http://www.linayachnin.com/img/lina_yachnin_facebook_profile.jpg"/><meta property="og:description" content="Lina Yachnin is a Canadian oil & watercolour artist who paints landscapes, floral arrangements, and abstract images."/><meta property="og:url" content="http://www.linayachin.com"/><meta property="og:title" content="Abstract paintings by Lina Yachnin — Canadian Oil & Watercolour Artist"/><script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-88189548-1', 'auto');
  ga('send', 'pageview');

</script>
</head>
<body><!-- Main container -->
<div class="page-container">

<?php include 'source/navbar.php';?>

<!-- bloc-abstracts-banner -->
<div class="bloc b-parallax bgc-white-2 bg-Airport-Reflections d-bloc bg-l-edge banner" id="bloc-abstracts-banner">
	<div class="container bloc-lg">
		<div class="row">
			<div class="col-sm-12">
				<h1 class="mg-md mm-links tc-white-2">
					<strong>Abstracts</strong>
				</h1>
			</div>
		</div>
	</div>
</div>
<!-- bloc-abstracts-banner END -->

<!-- bloc-abstracts-watercolours -->
<div class="bloc bgc-white-2 l-bloc painting-text" id="bloc-abstracts-watercolours">
	<div class="container bloc-md">
		<div class="row">
			<div class="col-sm-12">
				<h2 class="text-center mg-md ">Watercolour</h2>

				<div class="divider-h">
					<span class="divider divider-half"></span>
				</div>

				<div class="row">
					<div class="col-sm-6">
						<div class="text-center">
							<a data-frame="dark-lb" data-lightbox="img/Red_Sky_at_Night.jpg" href="#">
								<img alt="Red Sky at Night" class="center-block landscape" src="img/Red_Sky_at_Night.jpg"/>
							</a>
						</div>
						<h3 class="mg-sm  text-center">Red Sky at Night</h3>
						<p class="text-center">16" x 20", framed<br />$350</p>
					</div>
					<div class="col-sm-6">
						<div class="text-center">
							<a data-frame="dark-lb" data-lightbox="img/A_Break_in_the_Storm.jpg" href="#">
								<img alt="A Break in the Storm (Sold)" class="center-block landscape" src="img/A_Break_in_the_Storm.jpg"/>
							</a>
						</div>
						<h3 class="mg-sm  text-center">A Break in the Storm (Sold)</h3>
					</div>
				</div>
				
				<div class="row row-move-down">
					<div class="col-sm-3">
						<a data-frame="dark-lb" data-lightbox="img/Shattered.jpg" href="#">
							<img alt="Light Through the Trees (Sold)" class="center-block portrait" src="img/Shattered.jpg"/>
						</a>
						<h3 class="mg-sm  text-center">Shattered (Sold)</h3>
					</div>

					<div class="col-sm-3">
						<a data-frame="dark-lb" data-lightbox="img/High_Falls.jpg" href="#">
							<img alt="High Falls (Sold)" class="center-block portrait" src="img/High_Falls.jpg"/>
						</a>
						<h3 class="mg-sm  text-center">High Falls (Sold)</h3>
					</div>

					<div class="col-sm-3">
						<a data-frame="dark-lb" data-lightbox="img/Trepidation.jpg" href="#">
							<img alt="Trepidation (Sold)" class="center-block portrait" src="img/Trepidation.jpg"/>
						</a>
						<h3 class="mg-sm  text-center">Trepidation (Sold)</h3>
					</div>

					<div class="col-sm-3">
						<a data-frame="dark-lb" data-lightbox="img/Light_Through_the_Trees.jpg" href="#">
							<img alt="Light Through the Trees (Sold)" class="center-block portrait" src="img/Light_Through_the_Trees.jpg"/>
						</a>
						<h3 class="mg-sm  text-center">Light Through the Trees (Sold)</h3>
					</div>
				</div>

				<div class="row row-move-down">
					<div class="col-sm-3">
						<div class="text-center">
							<a data-frame="dark-lb" data-lightbox="img/Wind_in_the_Canyon.jpg" href="#">
								<img alt="Wind in the Canyon" class="center-block landscape" src="img/Wind_in_the_Canyon.jpg"/>
							</a>
						</div>
						<h3 class="mg-sm  text-center">Wind in the Canyon (Sold)</h3>
					</div>

					<div class="col-sm-3">
						<div class="text-center">
							<a data-frame="dark-lb" data-lightbox="img/Shipwrecked.jpg" href="#">
								<img alt="Shipwrecked (Sold)" class="center-block landscape" src="img/Shipwrecked.jpg"/>
							</a>
						</div>
						<h3 class="mg-sm  text-center">Shipwrecked (Sold)</h3>
					</div>

					<div class="col-sm-3">
						<a data-frame="dark-lb" data-lightbox="img/Airport_Reflections.jpg" href="#">
							<img alt="Airport Reflections (Sold)" class="center-block landscape" src="img/Airport_Reflections.jpg"/>
						</a>

						<h3 class="mg-sm  text-center">Airport Reflections (Sold)</h3>
					</div>

					<div class="col-sm-3">
						<a data-frame="dark-lb" data-lightbox="img/Before_the_Storm.jpg" href="#">
							<img alt="Before the Storm (Sold)" class="center-block landscape" src="img/Before_the_Storm.jpg"/>
						</a>

						<h3 class="mg-sm  text-center">Before the Storm (Sold)</h3>
					</div>
				</div>
				<div class="row row-move-down">
					<div class="col-sm-4">
						<div class="text-center">
							<a data-frame="dark-lb" data-lightbox="img/The_Urban_Landscape.jpg" href="#">
								<img alt="The Urban Landscape (Sold)" class="portrait center-block" src="img/The_Urban_Landscape.jpg"/>
							</a>
						</div>
						<h3 class="mg-sm  text-center">The Urban Landscape (Sold)</h3>
					</div>
					<div class="col-sm-4">
						<a href="#" data-lightbox="img/Held_by_the_Sun.jpg" data-frame="dark-lb"><img src="img/Held_by_the_Sun.jpg" class="center-block portrait" alt="Held by the Sun" /></a>
						<h3 class=" text-center mg-sm">
							Held by the Sun (Sold)
						</h3>
					</div>
					<div class="col-sm-4">
						<a href="#" data-lightbox="img/Window_through_distorted_glass.jpg" data-frame="dark-lb"><img src="img/Window_through_distorted_glass.jpg" class="center-block portrait" alt="Window through distorted glass" /></a>
						<h3 class=" text-center mg-sm">
							Window Through Distorted Glass (Sold)
						</h3>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- bloc-abstracts-watercolours END -->

<?php include 'source/social_footer.php';?>

</div>
<!-- Main container END --></body>
<!-- Google Analytics --><!-- Google Analytics END --></html>