<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>Lina Yachnin &ndash; Abstracts</title>
	<?php include 'source/meta_header.php';?>
	<meta property="og:title" content="Abstract paintings by Lina Yachnin — Canadian Oil & Watercolour Artist">
	<?php structured_data_from_csv(array("paintings/abstracts_watercolours.csv"));?>
</head>
<body><!-- Main container -->
<div class="page-container">

<?php include 'source/navbar.php';?>

<!-- bloc-abstracts-banner -->
<div class="bloc b-parallax bgc-main-bg bg-Airport-Reflections bg-l-edge banner" id="bloc-abstracts-banner">
	<div class="container bloc-lg">
		<div class="row">
			<div class="col-sm-12">
				<h1 class="mg-md over-image-title-text tc-white">
					<strong>Abstracts</strong>
				</h1>
			</div>
		</div>
	</div>
</div>
<!-- bloc-abstracts-banner END -->

<!-- bloc-abstracts-watercolours -->
<?php generate_paintings("watercolour", "paintings/abstracts_watercolours.csv", $curpage[0], "accent-bg");?>
<!-- bloc-abstracts-watercolours END -->

<?php include 'source/social_footer.php';?>

</div>

<?php include 'source/scripts_footer.php';?>
<!-- Main container END --></body>
<!-- Google Analytics --><!-- Google Analytics END --></html>