<!doctype html>
<html>
<head>
	<meta charset="utf-8">
	<title>Lina Yachnin &ndash; Available Works</title>
	<?php include 'source/meta_header.php';?>
	<meta property="og:title" content="Available works by Lina Yachnin — Canadian Oil & Watercolour Artist"/>
</head>
<body><!-- Main container -->
<div class="page-container">

<?php include 'source/navbar.php';?>

<!-- bloc-available_works-banner -->
<div class="bloc b-parallax bgc-white-2 l-bloc bg-b-edge banner bg-Huron-Shadows" id="bloc-available_works-banner">
	<div class="container bloc-lg">
		<div class="row">
			<div class="col-sm-12">
				<h1 class="mg-md mm-links tc-white-2">
					<strong>Available Works</strong>
				</h1>
			</div>
		</div>
	</div>
</div>
<!-- bloc-available_works-banner END -->

<!-- bloc-available_works-announce -->
<div class="bloc bgc-white-2 l-bloc" id="bloc-available_works-announce">
	<div class="container bloc-lg">
		<div class="row">
			<div class="col-sm-12">
				<p class="text-center ">
					The following are paintings that are for sale, and can be viewed and purchased at the <a href="http://www.galerieoldchelsea.ca" class="text-center" style="display: inline">Galerie Old Chelsea.</a><br/>
				</p>
			</div>
		</div>
	</div>
</div>
<!-- bloc-available_works-announce END -->

<!-- bloc-available_works-watercolours -->
<div class="bloc bgc-white-2 l-bloc painting-text" id="bloc-available_works-watercolours">
	<div class="container bloc-sm">
		<div class="row">
			<div class="col-sm-12">
				<h2 class="text-center mg-md ">Watercolour</h2>

				<div class="divider-h">
					<span class="divider divider-half"></span>
				</div>
				
				<div class="row">
					<div class="col-sm-6">
						<div class="text-center">
							<a data-frame="dark-lb" data-lightbox="img/Red_Sky_at_Night.jpg" href="#">
								<img alt="Red Sky at Night" class="center-block landscape" src="img/Red_Sky_at_Night.jpg"/>
							</a>
						</div>
						<h3 class="mg-sm  text-center">Red Sky at Night</h3>
						<p class="text-center">16" x 20", framed<br />$350</p>
					</div>
					<div class="col-sm-6">
						<a href="#" data-lightbox="img/Portbou_Spain.jpg" data-frame="dark-lb"><img src="img/Portbou_Spain.jpg" class="center-block landscape" alt="Portbou, Spain" /></a>
						<h3 class=" text-center mg-sm">
							Portbou, Spain
						</h3>
						<p class=" text-center">
							15" x 20", framed<br/>$550
						</p>
					</div>
				</div>

				<div class="row row-move-down">
					<div class="col-sm-12">
						<a href="#" data-lightbox="img/Coquelicots.jpg" data-frame="dark-lb"><img src="img/Coquelicots.jpg" class="center-block portrait" alt="Coquelicots" /></a>
						<h3 class=" text-center mg-sm">
							Coquelicots
						</h3>
						<p class=" text-center">
							8" x 11", framed<br/>$225
						</p>
					</div>
				</div>
				
				<div class="row row-move-down">
					<div class="col-sm-12">
						<a href="#" data-lightbox="img/Ancient_Doors.jpg" data-frame="dark-lb"><img src="img/Ancient_Doors.jpg" class="center-block landscape hidden-sm hidden-md hidden-lg" alt="Ancient Doors" /></a>
						<a href="#" data-lightbox="img/Ancient_Doors.jpg" data-frame="dark-lb"><img src="img/Ancient_Doors.jpg" class="center-block hidden-xs" style="width: 680px" alt="Ancient Doors" /></a>
						<h3 class=" text-center mg-sm">
							Ancient Doors
						</h3>
						<p class=" text-center">
							32" x 16", framed<br />$475
						</p>
					</div>
				</div>

			</div>
		</div>	
	</div>
</div>
<!-- bloc-available_works-watercolours END -->

<!-- bloc-available_works-oils -->
<div class="bloc bgc-gainsboro l-bloc painting-text" id="bloc-available_works-oils">
	<div class="container bloc-md">
		<div class="row">
			<div class="col-sm-12">
				<h2 class="text-center mg-md ">Oil</h2>

				<div class="divider-h">
					<span class="divider divider-half"></span>
				</div>

				<div class="row">
					<div class="col-sm-3">
						<a data-frame="dark-lb" data-lightbox="img/Sunset_Through_the_Trees_2.jpg" href="#">
							<img alt="Sunset Through the Trees" class="center-block landscape" src="img/Sunset_Through_the_Trees_2.jpg"/>
						</a>
						<h3 class="mg-sm  text-center">Sunset Through the Trees</h3>
						<p class="text-center">12" x 12" each<br/>$200 each or 2 for $375<br/>Oil on gallery canvas</p>
					</div>
					<div class="col-sm-3">
						<a data-frame="dark-lb" data-lightbox="img/Huron_Shadows.jpg" href="#">
							<img alt="Huron Shadows" class="center-block landscape" src="img/Huron_Shadows.jpg"/>
						</a>
						<h3 class="mg-sm  text-center">Huron Shadows</h3>
						<p class="text-center">10" x 10", oil on gallery canvas<br />$180</p>
					</div>
					<div class="col-sm-3">
						<a data-frame="dark-lb" data-lightbox="img/Homeward_2.jpg" href="#">
							<img alt="Homeward 2" class="center-block landscape" src="img/Homeward_2.jpg"/>
						</a>
						<h3 class="mg-sm  text-center">Homeward 2</h3>
						<p class="text-center">12" x 18", oil on gallery canvas<br />$275</p>
					</div>
					<div class="col-sm-3">
						<a href="#" data-lightbox="img/Autumn_Through_the_Trees.jpg" data-frame="dark-lb"><img src="img/Autumn_Through_the_Trees.jpg" class="center-block landscape" alt="Autumn Through the Trees" /></a>
						<h3 class="mg-sm  text-center">
							Autumn Through the Trees
						</h3>
						<p class=" text-center">24" x 24", Oil on gallery canvas<br />$550</p>
					</div>
				</div>
				
				<div class="row row-move-down">
					<div class="col-sm-6">
						<a data-frame="dark-lb" data-lightbox="img/Coastal_Sunset.jpg" href="#">
							<img alt="Coastal Sunset" class="center-block portrait" src="img/Coastal_Sunset.jpg"/>
						</a>

						<h3 class="mg-sm  text-center">Coastal Sunset</h3>
						<p class="text-center">24" x 48", framed<br />$1,100</p>
					</div>
					<div class="col-sm-6">
						<a data-frame="dark-lb" data-lightbox="img/Winter_Shadows.jpg" href="#">
							<img alt="Winter Shadows" class="center-block portrait" src="img/Winter_Shadows.jpg"/>
						</a>

						<h3 class="mg-sm  text-center">Winter Shadows</h3>
						<p class="text-center">10" x 20", oil on gallery canvas<br />$295</p>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- bloc-available_works-oils END -->

<?php include 'source/social_footer.php';?>

</div>
<!-- Main container END --></body>
<!-- Google Analytics --><!-- Google Analytics END --></html>