<!doctype html>
<html>
<head>
	<meta charset="utf-8">
	<title>Lina Yachnin &ndash; Available Works</title>
	<?php include 'source/meta_header.php';?>
	<meta property="og:title" content="Available works by Lina Yachnin — Canadian Oil & Watercolour Artist"/>
</head>
<body><!-- Main container -->
<div class="page-container">

<?php include 'source/navbar.php';?>

<!-- bloc-available_works-banner -->
<div class="bloc b-parallax bgc-main-bg l-bloc bg-b-edge banner bg-Huron-Shadows" id="bloc-available_works-banner">
	<div class="container bloc-lg">
		<div class="row">
			<div class="col-sm-12">
				<h1 class="mg-md mm-links tc-white">
					<strong>Available Works</strong>
				</h1>
			</div>
		</div>
	</div>
</div>
<!-- bloc-available_works-banner END -->

<!-- bloc-available_works-announce -->
<div class="bloc bgc-main-bg l-bloc" id="bloc-available_works-announce">
	<div class="container bloc-lg">
		<div class="row">
			<div class="col-sm-12">
				<h6 class="text-center ">
					The following are paintings that are for sale, and can be viewed and purchased at the <a href="http://www.galerieoldchelsea.ca" class="text-center" style="display: inline">Galerie Old Chelsea.</a><br/>
				</h6>
			</div>
		</div>
	</div>
</div>
<!-- bloc-available_works-announce END -->

<!-- bloc-available_works-watercolours -->
<div class="bloc bgc-main-bg l-bloc painting-text" id="bloc-available_works-watercolours">
	<div class="container bloc-sm">
		<div class="row">
			<div class="col-sm-12">
				<h2 class="text-center mg-md ">Watercolour</h2>

				<div class="divider-h">
					<span class="divider divider-half"></span>
				</div>
				
				<div class="row">
					<div class="col-sm-6">
						<a href="#" data-lightbox="img/Bouquet_in_Blue.jpg" data-frame="dark-lb"><img src="img/Bouquet_in_Blue.jpg" class="center-block portrait" alt="Bouquet in Blue" /></a>
						<h4 class=" text-center mg-sm">
							Bouquet in Blue
						</h4>
						<p class="text-center">
							11" x 14"<br/>
							Watercolour on paper, framed<br />
							$195
						</p>
					</div>
					<div class="col-sm-6">
						<a href="#" data-lightbox="img/Emergence.jpg" data-frame="dark-lb"><img src="img/Emergence.jpg" class="center-block portrait" alt="Emergence" /></a>
						<h4 class=" text-center mg-sm">
							Emergence
						</h4>
						<p class=" text-center">
							16" x 20", framed<br />$325
						</p>
					</div>
				</div>
				<div class="row row-move-down">
					<div class="col-sm-12">
						<a href="#" data-lightbox="img/Coastal_View.jpg" data-frame="dark-lb"><img src="img/Coastal_View.jpg" class="center-block landscape" alt="Coastal View" /></a>
						<h4 class=" text-center mg-sm">
							Coastal View
						</h4>
						<p class=" text-center">
							30" x 38"<br/>
							Watercolour on paper, framed<br />
							$950
						</p>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- bloc-available_works-watercolours END -->

<!-- bloc-available_works-oils -->
<div class="bloc bgc-accent-bg l-bloc painting-text" id="bloc-available_works-oils">
	<div class="container bloc-md">
		<div class="row">
			<div class="col-sm-12">
				<h2 class="text-center mg-md ">Oil</h2>

				<div class="divider-h">
					<span class="divider divider-half"></span>
				</div>

				<div class="row">
					<div class="col-sm-12">
						<a data-frame="dark-lb" data-lightbox="img/Seaside_Retreat.jpg" href="#">
							<img alt="Seaside Retreat" class="center-block landscape" src="img/Seaside_Retreat.jpg"/>
						</a>
						<h4 class="mg-sm  text-center">Seaside Retreat</h4>
						<p class="text-center">
							8" x 8" each<br/>
							Oil on gallery canvas<br />
							$160 each or 3 for $420
						</p>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- bloc-available_works-oils END -->

<?php include 'source/social_footer.php';?>

</div>

<?php include 'source/scripts_footer.php';?>
<!-- Main container END --></body>
<!-- Google Analytics --><!-- Google Analytics END --></html>