<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
	<title>Lina Yachnin – Contact Us</title>
	<?php include 'source/meta_header.php';?>
	<meta property="og:title" content="Contact Lina Yachnin — Canadian Oil & Watercolour Artist">
</head>
<body>
<!-- Main container -->
<div class="page-container">

<?php include 'source/navbar.php';?>

<!-- bloc-contact-banner -->
<div class="bloc b-parallax bgc-main-bg bg-Before-the-Storm l-bloc bg-l-edge banner" id="bloc-contact-banner">
	<div class="container bloc-lg">
		<div class="row">
			<div class="col-sm-12">
				<h1 class="mg-md over-image-title-text tc-white">
					<strong>Contact</strong>
				</h1>
			</div>
		</div>
	</div>
</div>
<!-- bloc-contact-banner END -->

<!-- bloc-contact-form -->
<div class="bloc bgc-accent-bg l-bloc" id="bloc-contact-form">
	<div class="container bloc-sm">
		<div class="row">
			<div class="col-sm-12">
				<h6 class=" text-center paragraph-contact">
					Send us a message and we&rsquo;ll get back to you as soon as possible.
				</h6>
				<form id="form_2" novalidate>
					<div class="form-group">
						<label class="labels-form">
							Name
						</label>
						<input id="name" class="form-control" required>
					</div>
					<div class="form-group">
						<label class="labels-form">
							Email
						</label>
						<input id="email" class="form-control" type="email" required>
					</div>
					<div class="form-group">
						<label class="labels-form">
							Message
						</label><textarea id="message" class="form-control" rows="4" cols="50" required></textarea>
					</div>
					<button class="bloc-button btn btn-lg pull-right submit-button-color" type="submit">
						Submit
					</button>
				</form>
			</div>
		</div>
	</div>
</div>
<!-- bloc-contact-form END -->

<?php include 'source/social_footer.php';?>

</div>
<!-- Main container END -->

<?php include 'source/scripts_footer.php';?>
<script src="./js/jqBootstrapValidation.js"></script>
<script src="./js/formHandler.js"></script>
</body>

<!-- Google Analytics -->

<!-- Google Analytics END -->

</html>
