<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="keywords" content="Ottawa watercolour oil artist paint painting art Canada landscape floral abstract for sale local Quebec Gatineau Outaouais affordable buy purchase order cheap gift present Galerie Old Chelsea gallery cadeau peinture artiste huile aquarelle fleurs abstrait dessin paysage abordable commander acheter Wakefield">
    <meta name="description" content="Lina Yachnin is a Canadian oil & watercolour artist who paints landscapes, floral arrangements, and abstract images.">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=0">
    <link rel="shortcut icon" type="image/png" href="favicon.ico" />
    
	<link rel="stylesheet" type="text/css" href="./css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="style.css"><link rel='stylesheet' href='./css/font-awesome.min.css'/><link href='http://fonts.googleapis.com/css?family=helvetica&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
    
	<script src="./js/jquery-2.1.0.min.js"></script>
	<script src="./js/bootstrap.min.js"></script>
	<script src="./js/blocs.min.js"></script>
	<script src="./js/jqBootstrapValidation.js"></script>
	<script src="./js/formHandler.js"></script>
    <title>Lina Yachnin – Contact Us</title>

     <meta property="og:image" content="http://www.linayachnin.com/img/lina_yachnin_facebook_profile.jpg"/>
    <meta property="og:description" content="Lina Yachnin is a Canadian oil & watercolour artist who paints landscapes, floral arrangements, and abstract images."/>
<meta property="og:url" content="http://www.linayachin.com"/>
<meta property="og:title" content="Contact Lina Yachnin — Canadian Oil & Watercolour Artist"/>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-88189548-1', 'auto');
  ga('send', 'pageview');

</script>

</head>
<body>
<!-- Main container -->
<div class="page-container">
    
<!-- bloc-navbar-mobile -->
<div class="bloc hidden-sm hidden-lg hidden-md bgc-gray-x11-gray l-bloc" id="bloc-navbar-mobile">
	<div class="container">
		<nav class="navbar row">
			<div class="navbar-header">
				<a href="http://www.facebook.com/linayachninart/" class="icon-padding" target="_blank"><span class="fa fa-facebook icon-md pull-left"></span></a>
				<button id="nav-toggle" type="button" class="ui-navbar-toggle navbar-toggle" data-toggle="collapse" data-target=".navbar-1">
					<span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
				</button>
			</div>
			<div class="navbar-collapse navbar-1 collapse">
				<ul class="site-navigation nav navbar-nav list-dimensions">
					<li>
						<a href="index">Home</a>
					</li>
					<li>
						<a href="exhibitions">Exhibitions</a>
					</li>
					<li>
						<a href="about">About</a>
					</li>
					<li>
						<a href="available_works">Available Works</a>
					</li>
					<li>
						<a href="florals">Florals</a>
					</li>
					<li>
						<a href="landscapes">Landscapes</a>
					</li>
					<li>
						<a href="abstracts">Abstracts</a>
					</li>
					<li>
						<a href="urbanscapes">Urbanscapes</a>
					</li>
					<li>
						<a href="contact">Contact</a>
					</li>
				</ul>
			</div>
		</nav>
	</div>
</div>
<!-- bloc-navbar-mobile END -->

<!-- bloc-navbar-contact-desktop -->
<div class="bloc hidden-xs hidden-sm bgc-white l-bloc pad-top-nav" id="bloc-navbar-contact-desktop">
	<div class="container bloc-sm">
		<div class="row">
			<div class="col-sm-4">
				<a href="index"><img src="img/short-sig.jpg" class="img-responsive" width="254" alt="Lina Yachnin"/></a>
			</div>
			<div class="col-sm-8">
				<ul class="list-unstyled list-container list-horizontal-layout">
					<li>
						<a href="index">Home</a>
					</li>
					<li>
						<a href="exhibitions">Exhibitions</a>
					</li>
					<li>
						<a href="about">About</a>
					</li>
					<li>
						<a href="available_works">Available Works</a>
					</li>
					<li>
						<a href="florals">Florals</a>
					</li>
					<li>
						<a href="landscapes">Landscapes</a>
					</li>
					<li>
						<a href="abstracts">Abstracts</a>
					</li>
					<li>
						<a href="urbanscapes">Urbanscapes</a>
					</li>
				</ul>
			</div>
		</div>
	</div>
</div>
<!-- bloc-navbar-contact-desktop END -->

<!-- bloc-navbar-contact-tablet -->
<div class="bloc hidden-xs hidden-lg hidden-md bgc-white l-bloc" id="bloc-navbar-contact-tablet">
	<div class="container bloc-sm">
		<div class="row">
			<div class="col-sm-6">
				<a href="index"><img src="img/short-sig.jpg" class="img-responsive center-block" width="261" alt="Lina Yachnin"/></a>
			</div>
			<div class="col-sm-6">
				<ul class="list-unstyled list-horizontal-layout">
					<li>
						<a href="index">Home</a>
					</li>
					<li>
						<a href="exhibitions">Exhibitions</a>
					</li>
					<li>
						<a href="about">About</a>
					</li>
					<li>
						<a href="available_works">Available Works</a>
					</li>
					<li>
						<a href="florals">Florals</a>
					</li>
					<li>
						<a href="landscapes">Landscapes</a>
					</li>
					<li>
						<a href="abstracts">Abstracts</a>
					</li>
					<li>
						<a href="urbanscapes">Urbanscapes</a>
					</li>
				</ul>
			</div>
		</div>
	</div>
</div>
<!-- bloc-navbar-contact-tablet END -->

<!-- bloc-contact-banner -->
<div class="bloc b-parallax bgc-white-2 bg-Before-the-Storm d-bloc bg-l-edge banner" id="bloc-contact-banner">
	<div class="container bloc-lg">
		<div class="row">
			<div class="col-sm-12">
				<h1 class="mg-md mm-links tc-white-2">
					<strong>Contact</strong>
				</h1>
			</div>
		</div>
	</div>
</div>
<!-- bloc-contact-banner END -->

<!-- bloc-contact-form -->
<div class="bloc bgc-gainsboro l-bloc" id="bloc-contact-form">
	<div class="container bloc-sm">
		<div class="row">
			<div class="col-sm-12">
				<p class=" text-center paragraph-contact">
					Send us a message and we&rsquo;ll get back to you as soon as possible.
				</p>
				<form id="form_2" novalidate>
					<div class="form-group">
						<label class="labels-form">
							Name
						</label>
						<input id="name" class="form-control" required />
					</div>
					<div class="form-group">
						<label class="labels-form">
							Email
						</label>
						<input id="email" class="form-control" type="email" required />
					</div>
					<div class="form-group">
						<label class="labels-form">
							Message
						</label><textarea id="message" class="form-control" rows="4" cols="50" required></textarea>
					</div> 
					<button class="bloc-button btn btn-lg pull-right btn-dark-lava" type="submit">
						Submit
					</button>
				</form>
			</div>
		</div>
	</div>
</div>
<!-- bloc-contact-form END -->

<!-- Footer - bloc-social-desktop -->
<div class="bloc hidden-xs hidden-sm bgc-white l-bloc" id="bloc-social-desktop">
	<div class="container bloc-md">
		<div class="row padding-footer">
			<div class="col-sm-3 col-sm-offset-3">
				<div class="text-center">
					<a href="index"></a>
					<div class="text-center">
						<a href="index"></a><a href="http://facebook.com" target="_blank"></a>
						<div class="text-center pull-left">
							<a href="http://facebook.com" target="_blank"></a><a href="http://www.facebook.com/linayachninart/" target="_blank"><span class="fa fa-facebook icon-lg icon-dark-lava"></span></a>
						</div>
					</div>
				</div>
			</div>
			<div class="col-sm-3">
				<div class="text-center">
					<a href="index"></a>
					<div class="text-center">
						<a href="index"></a><a href="https://www.linkedin.com/in/lina-yachnin-54a9a28a" target="_blank"><span class="fa fa-linkedin icon-lg pull-left icon-dark-lava"></span></a>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- Footer - bloc-social-desktop END -->

<!-- Footer - bloc-social-tablet -->
<div class="bloc hidden-xs hidden-lg hidden-md bgc-white l-bloc" id="bloc-social-tablet">
	<div class="container bloc-md">
		<div class="row footer-tablet-padding">
			<div class="col-sm-3 col-sm-offset-3">
				<div class="text-center">
					<a href="index"></a>
					<div class="text-center">
						<a href="index"></a><a href="http://facebook.com" target="_blank"></a>
						<div class="text-center pull-left">
							<a href="http://facebook.com" target="_blank"></a><a href="http://www.facebook.com/linayachninart/" target="_blank"><span class="fa fa-facebook icon-lg icon-dark-lava"></span></a>
						</div>
					</div>
				</div>
			</div>
			<div class="col-sm-3">
				<div class="text-center">
					<a href="index"></a>
					<div class="text-center">
						<a href="index"></a><a href="https://www.linkedin.com/in/lina-yachnin-54a9a28a" target="_blank"><span class="fa fa-linkedin icon-dark-lava icon-lg pull-left"></span></a>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- Footer - bloc-social-tablet END -->
</div>
<!-- Main container END -->
    

</body>
    
<!-- Google Analytics -->
 
<!-- Google Analytics END -->

</html>
