<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="keywords" content="Ottawa watercolour oil artist paint painting art Canada landscape floral abstract for sale local Quebec Gatineau Outaouais affordable buy purchase order cheap gift present Galerie Old Chelsea gallery cadeau peinture artiste huile aquarelle fleurs abstrait dessin paysage abordable commander acheter Wakefield">
    <meta name="description" content="Lina Yachnin is a Canadian oil & watercolour artist who paints landscapes, floral arrangements, and abstract images.">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=0">
    <link rel="shortcut icon" type="image/png" href="favicon.ico" />
    
	<link rel="stylesheet" type="text/css" href="./css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="style.css"><link rel='stylesheet' href='./css/font-awesome.min.css'/><link href='http://fonts.googleapis.com/css?family=helvetica&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
    
	<script src="./js/jquery-2.1.0.min.js"></script>
	<script src="./js/bootstrap.min.js"></script>
	<script src="./js/blocs.min.js"></script>
	<script src="./js/jqBootstrapValidation.js"></script>
	<script src="./js/formHandler.js"></script>
    <title>Lina Yachnin – Contact Us</title>

     <meta property="og:image" content="http://www.linayachnin.com/img/lina_yachnin_facebook_profile.jpg"/>
    <meta property="og:description" content="Lina Yachnin is a Canadian oil & watercolour artist who paints landscapes, floral arrangements, and abstract images."/>
<meta property="og:url" content="http://www.linayachin.com"/>
<meta property="og:title" content="Contact Lina Yachnin — Canadian Oil & Watercolour Artist"/>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-88189548-1', 'auto');
  ga('send', 'pageview');

</script>

</head>
<body>
<!-- Main container -->
<div class="page-container">
    
<?php include 'source/navbar.php';?>

<!-- bloc-contact-banner -->
<div class="bloc b-parallax bgc-white-2 bg-Before-the-Storm d-bloc bg-l-edge banner" id="bloc-contact-banner">
	<div class="container bloc-lg">
		<div class="row">
			<div class="col-sm-12">
				<h1 class="mg-md mm-links tc-white-2">
					<strong>Contact</strong>
				</h1>
			</div>
		</div>
	</div>
</div>
<!-- bloc-contact-banner END -->

<!-- bloc-contact-form -->
<div class="bloc bgc-gainsboro l-bloc" id="bloc-contact-form">
	<div class="container bloc-sm">
		<div class="row">
			<div class="col-sm-12">
				<p class=" text-center paragraph-contact">
					Send us a message and we&rsquo;ll get back to you as soon as possible.
				</p>
				<form id="form_2" novalidate>
					<div class="form-group">
						<label class="labels-form">
							Name
						</label>
						<input id="name" class="form-control" required />
					</div>
					<div class="form-group">
						<label class="labels-form">
							Email
						</label>
						<input id="email" class="form-control" type="email" required />
					</div>
					<div class="form-group">
						<label class="labels-form">
							Message
						</label><textarea id="message" class="form-control" rows="4" cols="50" required></textarea>
					</div> 
					<button class="bloc-button btn btn-lg pull-right btn-dark-lava" type="submit">
						Submit
					</button>
				</form>
			</div>
		</div>
	</div>
</div>
<!-- bloc-contact-form END -->

<?php include 'source/social_footer.php';?>

</div>
<!-- Main container END -->
    

</body>
    
<!-- Google Analytics -->
 
<!-- Google Analytics END -->

</html>
