<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>Lina Yachnin – Upcoming Exhibitions</title>
	<?php include 'source/meta_header.php';?>
	<meta property="og:title" content="Upcoming exhibition for Lina Yachnin — Canadian Oil & Watercolour Artist"/>
</head>
<body>
<!-- Main container -->
<div class="page-container">
    
<?php include 'source/navbar.php';?>

<!-- bloc-exhibition-banner -->
<div class="bloc b-parallax bgc-white-2 bg-After-the-Storm l-bloc bg-center banner" id="bloc-exhibition-banner">
	<div class="container bloc-lg">
		<div class="row">
			<div class="col-sm-12">
				<h1 class="mg-md tc-white-2 mm-links">
					<strong><?php echo $ex_title;?></strong>
				</h1>
			</div>
		</div>
	</div>
</div>
<!-- bloc-exhibition-banner END -->

<!-- bloc-exhibition-announce -->
<div class="bloc bgc-white-2 l-bloc" id="bloc-exhibition-announce">
	<div class="container bloc-lg">
		<div class="row">
			<div class="col-sm-12">
				<p class="text-center ">
					<?php echo $exhibition_text;?>
				</p>
			</div>
		</div>
	</div>
</div>
<!-- bloc-exhibition-announce END -->

<?php
	if ( $exhibition ) {
			include 'exhibitions_paintings.phtml';
		}
?>

<?php include 'source/social_footer.php';?>

</div>
<!-- Main container END -->
    

</body>
    
<!-- Google Analytics -->
 
<!-- Google Analytics END -->

</html>
