<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="keywords" content="Ottawa watercolour oil artist paint painting art Canada landscape floral abstract for sale local Quebec Gatineau Outaouais affordable buy purchase order cheap gift present Galerie Old Chelsea gallery cadeau peinture artiste huile aquarelle fleurs abstrait dessin paysage abordable commander acheter Wakefield">
    <meta name="description" content="Lina Yachnin is a Canadian oil & watercolour artist who paints landscapes, floral arrangements, and abstract images.">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=0">
    <link rel="shortcut icon" type="image/png" href="favicon.ico" />
    
	<link rel="stylesheet" type="text/css" href="./css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="style.css"><link rel='stylesheet' href='./css/font-awesome.min.css'/><link href='http://fonts.googleapis.com/css?family=helvetica&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
    
	<script src="./js/jquery-2.1.0.min.js"></script>
	<script src="./js/bootstrap.min.js"></script>
	<script src="./js/blocs.min.js"></script>
    <title>Lina Yachnin – Upcoming Exhibitions</title>

 <meta property="og:image" content="http://www.linayachnin.com/img/lina_yachnin_facebook_profile.jpg"/>
    <meta property="og:description" content="Lina Yachnin is a Canadian oil & watercolour artist who paints landscapes, floral arrangements, and abstract images."/>
<meta property="og:url" content="http://www.linayachin.com"/>
<meta property="og:title" content="Upcoming exhibition for Lina Yachnin — Canadian Oil & Watercolour Artist"/>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-88189548-1', 'auto');
  ga('send', 'pageview');

</script>

</head>
<body>
<!-- Main container -->
<div class="page-container">
    
<?php include 'source/navbar.php';?>

<!-- bloc-exhibition-banner -->
<div class="bloc b-parallax bgc-white-2 bg-After-the-Storm l-bloc bg-center banner" id="bloc-exhibition-banner">
	<div class="container bloc-lg">
		<div class="row">
			<div class="col-sm-12">
				<h1 class="mg-md tc-white-2 mm-links">
					<!--<strong>Upcoming Exhibitions</strong>-->
					<strong>Exhibitions</strong>
				</h1>
			</div>
		</div>
	</div>
</div>
<!-- bloc-exhibition-banner END -->

<!-- bloc-exhibition-announce -->
<div class="bloc bgc-white-2 l-bloc" id="bloc-exhibition-announce">
	<div class="container bloc-lg">
		<div class="row">
			<div class="col-sm-12">
				<p class="text-center ">
					<i>Passerelle</i>, or <i>Gateway</i>, is a show representing my latest journeys along the coast of Spain, Sweden and the beautiful interior of Quebec. Whether they be landscapes, cityscapes or abstracts, I hope to communicate a strong emotional response through the common elements of colour, composition and design. Hoping to inspire you, the viewer, the way these places have inspired me.<br/><br/>
					Paintings that are still available from <i>Passerelle</i> can be viewed at the <a href="http://www.galerieoldchelsea.ca" class="text-center" style="display: inline">Galerie Old Chelsea.</a><br/>
				</p>
			</div>
		</div>
	</div>
</div>
<!-- bloc-exhibition-announce END -->

<!-- bloc-exhibitions-oils -->
<div class="bloc bgc-white-2 l-bloc painting-text hidden-all" id="bloc-exhibitions-oils">
	<div class="container bloc-md">
		<div class="row">
			<div class="col-sm-12">
				<h2 class="text-center mg-md ">
					Oil
				</h2>
				<div class="divider-h">
					<span class="divider divider-half"></span>
				</div>

				<div class="row">
					<div class="col-sm-4">
						<a href="#" data-lightbox="img/.jpg" data-frame="dark-lb"><img src="img/.jpg" class="center-block landscape" alt="Sundown" /></a>
						<h3 class="mg-sm  text-center">
							Sundown (Sold)
						</h3>
					</div>
					<div class="col-sm-4">
						<a href="#" data-lightbox="img/.jpg" data-frame="dark-lb"><img src="img/.jpg" class="center-block landscape" alt="Autumn Through the Trees" /></a>
						<h3 class="mg-sm  text-center">
							Autumn Through the Trees
						</h3>
						<p class=" text-center">Oil on gallery canvas<br />24" x 24"</p>
					</div>
					<div class="col-sm-4">
						<a href="#" data-lightbox="img/.jpg" data-frame="dark-lb"><img src="img/.jpg" class="center-block landscape" alt="Homeward" /></a>
						<h3 class="mg-sm  text-center">
							Homeward (Sold)
						</h3>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- bloc-exhibitions-oils END -->

<!-- bloc-exhibitions-watercolours -->
<div class="bloc bgc-gainsboro l-bloc painting-text hidden-all" id="bloc-exhibitions-watercolours">
	<div class="container bloc-md">
		<div class="row">
			<div class="col-sm-12">
				<h2 class="text-center mg-md ">
					Watercolour
				</h2>
				<div class="divider-h">
					<span class="divider divider-half"></span>
				</div>
				<div class="row">
					<div class="col-sm-3">
						<a href="#" data-lightbox="img/.jpg" data-frame="dark-lb"><img src="img/.jpg" class="center-block portrait" alt="Held by the Sun" /></a>
						<h3 class=" text-center mg-sm">
							Held by the Sun (Sold)
						</h3>
					</div>
					<div class="col-sm-3">
						<a href="#" data-lightbox="img/.jpg" data-frame="dark-lb"><img src="img/.jpg" class="center-block portrait" alt="Window through distorted glass" /></a>
						<h3 class=" text-center mg-sm">
							Window Through Distorted Glass (Sold)
						</h3>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- bloc-exhibitions-watercolours END -->

<?php include 'source/social_footer.php';?>

</div>
<!-- Main container END -->
    

</body>
    
<!-- Google Analytics -->
 
<!-- Google Analytics END -->

</html>
