<!-- bloc-exhibitions-oils -->
<div class="bloc bgc-white-2 l-bloc painting-text hidden-all" id="bloc-exhibitions-oils">
	<div class="container bloc-md">
		<div class="row">
			<div class="col-sm-12">
				<h2 class="text-center mg-md ">
					Oil
				</h2>
				<div class="divider-h">
					<span class="divider divider-half"></span>
				</div>

				<div class="row">
					<div class="col-sm-4">
						<a href="#" data-lightbox="img/.jpg" data-frame="dark-lb"><img src="img/.jpg" class="center-block landscape" alt="Sundown" /></a>
						<h3 class="mg-sm  text-center">
							Sundown (Sold)
						</h3>
					</div>
					<div class="col-sm-4">
						<a href="#" data-lightbox="img/.jpg" data-frame="dark-lb"><img src="img/.jpg" class="center-block landscape" alt="Autumn Through the Trees" /></a>
						<h3 class="mg-sm  text-center">
							Autumn Through the Trees
						</h3>
						<p class=" text-center">Oil on gallery canvas<br />24" x 24"</p>
					</div>
					<div class="col-sm-4">
						<a href="#" data-lightbox="img/.jpg" data-frame="dark-lb"><img src="img/.jpg" class="center-block landscape" alt="Homeward" /></a>
						<h3 class="mg-sm  text-center">
							Homeward (Sold)
						</h3>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- bloc-exhibitions-oils END -->

<!-- bloc-exhibitions-watercolours -->
<div class="bloc bgc-gainsboro l-bloc painting-text hidden-all" id="bloc-exhibitions-watercolours">
	<div class="container bloc-md">
		<div class="row">
			<div class="col-sm-12">
				<h2 class="text-center mg-md ">
					Watercolour
				</h2>
				<div class="divider-h">
					<span class="divider divider-half"></span>
				</div>
				<div class="row">
					<div class="col-sm-3">
						<a href="#" data-lightbox="img/.jpg" data-frame="dark-lb"><img src="img/.jpg" class="center-block portrait" alt="Held by the Sun" /></a>
						<h3 class=" text-center mg-sm">
							Held by the Sun (Sold)
						</h3>
					</div>
					<div class="col-sm-3">
						<a href="#" data-lightbox="img/.jpg" data-frame="dark-lb"><img src="img/.jpg" class="center-block portrait" alt="Window through distorted glass" /></a>
						<h3 class=" text-center mg-sm">
							Window Through Distorted Glass (Sold)
						</h3>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- bloc-exhibitions-watercolours END -->