<!-- bloc-index-exhibition-mobile -->
<div class="bloc hidden-lg hidden-md hidden-sm b-parallax <?php echo $ex_banner_style;?> bgc-main-bg l-bloc bg-center button-link" id="bloc-index-exhibition-mobile">
	<div class="container bloc-lg">
		<div class="row">
			<div class="col-sm-12">
				<a class="pull-left tc-white mm-links-mobile" href="exhibitions"><?php echo $ex_title;?></a>
			</div>
		</div>
	</div>
</div>
<!-- bloc-index-exhibition-mobile END -->

<!-- bloc-index-exhibition-desktop -->
<div class="bloc bloc-tile-2 hidden-xs <?php echo $ex_banner_style;?> l-bloc button-link" id="bloc-index-exhibition-desktop">
	<div class="container bloc-md">
		<div class="row">
			<div class="col-sm-12 text-center">
				<h2 class="mg-md text-center">
					<a class="tc-white over-image-title-text" href="exhibitions"><?php echo $ex_title;?></a>
				</h2>
			</div>
		</div>
	</div>
</div>
<!-- bloc-index-exhibition-desktop END -->