<!-- bloc-exhibitions-oils -->
<div class="bloc bgc-gainsboro l-bloc painting-text" id="bloc-exhibitions-oils">
	<div class="container bloc-md">
		<div class="row">
			<div class="col-sm-12">
				<h2 class="text-center mg-md ">
					Oil
				</h2>
				<div class="divider-h">
					<span class="divider divider-half"></span>
				</div>

				<div class="row">
					<div class="col-sm-3">
						<a href="#" data-lightbox="img/Coffee_Time.jpg" data-frame="dark-lb">
							<img src="img/Coffee_Time.jpg" class="center-block landscape" alt="Coffee Time" /></a>
						<h3 class=" text-center mg-sm">
							Coffee Time
						</h3>
						<p class="text-center">
							33" x 33"<br/>
							Oil on canvas, framed<br />
							$1050
						</p>
					</div>
					<div class="col-sm-3">
						<a href="#" data-lightbox="img/Night_Out.jpg" data-frame="dark-lb">
							<img src="img/Night_Out.jpg" class="center-block landscape" alt="Night Out" /></a>
						<h3 class=" text-center mg-sm">
							Night Out
						</h3>
						<p class="text-center">
							33" x 33"<br/>
							Oil on canvas<br />
							$1050
						</p>
					</div>
					<div class="col-sm-3">
						<a href="#" data-lightbox="img/Dining_Out.jpg" data-frame="dark-lb">
							<img src="img/Dining_Out.jpg" class="center-block landscape" alt="Dining Out" /></a>
						<h3 class=" text-center mg-sm">
							Dining Out
						</h3>
						<p class="text-center">
							27" x 40"<br/>
							Oil on gallery canvas, framed<br />
							$1250
						</p>
					</div>
					<div class="col-sm-3">
						<a href="#" data-lightbox="img/Colourful_Reflections_I.jpg" data-frame="dark-lb">
							<img src="img/Colourful_Reflections_I.jpg" class="center-block landscape" alt="Colourful Reflections I" /></a>
						<h3 class=" text-center mg-sm">
							Colourful Reflections I
						</h3>
						<p class="text-center">
							30" x 40"<br/>
							Oil on gallery canvas<br/>
							$1350
						</p>
					</div>
				</div>
				<div class="row row-move-down">
					<div class="col-sm-4">
						<a href="#" data-lightbox="img/Colourful_Reflections_II.jpg" data-frame="dark-lb">
							<img src="img/Colourful_Reflections_II.jpg" class="center-block portrait" alt="Colourful Reflections I" /></a>
						<h3 class=" text-center mg-sm">
							Colourful Reflections II
						</h3>
						<p class="text-center">
							18" x 36"<br/>
							Oil on gallery canvas<br/>
							$700
						</p>
					</div>
					<div class="col-sm-4">
						<a href="#" data-lightbox="img/Glacial_Walk.jpg" data-frame="dark-lb">
							<img src="img/Glacial_Walk.jpg" class="center-block portrait" alt="Glacial Walk /></a>
						<h3 class=" text-center mg-sm">
							Glacial Walk
						</h3>
						<p class="text-center">
							38" x 50"<br/>
							Oil on gallery canvas, framed<br/>
							$2100
						</p>
					</div>
					<div class="col-sm-4">
						<a href="#" data-lightbox="img/Shoreline_Walk.jpg" data-frame="dark-lb">
							<img src="img/Shoreline_Walk.jpg" class="center-block portrait" alt="Shoreline Walk /></a>
						<h3 class=" text-center mg-sm">
							Shoreline Walk
						</h3>
						<p class="text-center">
							33" x 33"<br/>
							Oil on gallery canvas<br/>
							$990
						</p>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- bloc-exhibitions-oils END -->

<!-- bloc-exhibitions-watercolours -->
<div class="bloc bgc-white-2 l-bloc painting-text" id="bloc-exhibitions-watercolours">
	<div class="container bloc-md">
		<div class="row">
			<div class="col-sm-12">
				<h2 class="text-center mg-md ">
					Watercolour
				</h2>
				<div class="divider-h">
					<span class="divider divider-half"></span>
				</div>
				<div class="row">
					<div class="col-sm-6">
						<a href="#" data-lightbox="img/Evening_in_Spain.jpg" data-frame="dark-lb"><img src="img/Evening_in_Spain.jpg" class="center-block landscape" alt="Evening in Spain" /></a>
						<h3 class=" text-center mg-sm">
							Evening in Spain
						</h3>
						<p class=" text-center">
							24" x 30"<br/>
							Watercolour, framed<br />
							$875
						</p>
					</div>
					<div class="col-sm-6">
						<a href="#" data-lightbox="img/Irish_Corner.jpg" data-frame="dark-lb"><img src="img/Irish_Corner.jpg" class="center-block landscape" alt="Irish Corner" /></a>
						<h3 class=" text-center mg-sm">
							Irish Corner
						</h3>
						<p class=" text-center">
							24" x 30"<br/>
							Watercolour, framed<br />
							$875
						</p>
					</div>
				</div>
				<div class="row row-move-down">
					<div class="col-sm-12">
						<a href="#" data-lightbox="img/Evening_Out_II.jpg" data-frame="dark-lb"><img src="img/Evening_Out_II.jpg" class="center-block portrait" alt="Evening Out II" /></a>
						<h3 class=" text-center mg-sm">
							Evening Out II
						</h3>
						<p class=" text-center">
							24" x 30"<br/>
							Watercolour, framed<br />
							$875
						</p>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- bloc-exhibitions-watercolours END -->