<!-- bloc-exhibitions-oils -->
<div class="bloc hidden-all bgc-white-2 l-bloc painting-text" id="bloc-exhibitions-oils">
	<div class="container bloc-md">
		<div class="row">
			<div class="col-sm-12">
				<h2 class="text-center mg-md ">
					Oil
				</h2>
				<div class="divider-h">
					<span class="divider divider-half"></span>
				</div>

				<div class="row">
					<div class="col-sm-4">
						<a href="#" data-lightbox="" data-frame="dark-lb"><img src="" class="center-block landscape" alt="Sundown" /></a>
						<h3 class="mg-sm  text-center">
							Sundown (Sold)
						</h3>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- bloc-exhibitions-oils END -->

<!-- bloc-exhibitions-watercolours -->
<div class="bloc bgc-white-2 l-bloc painting-text" id="bloc-exhibitions-watercolours">
	<div class="container bloc-md">
		<div class="row">
			<div class="col-sm-12">
				<h2 class="text-center mg-md ">
					Watercolour
				</h2>
				<div class="divider-h">
					<span class="divider divider-half"></span>
				</div>
				<div class="row">
					<div class="col-sm-6">
						<a href="#" data-lightbox="img/A_Break_in_the_Storm_Landscape.jpg" data-frame="dark-lb"><img src="img/A_Break_in_the_Storm_Landscape.jpg" class="center-block landscape" alt="A Break in the Storm" /></a>
						<h3 class=" text-center mg-sm">
							A Break in the Storm
						</h3>
						<p class=" text-center">
							8" x 11", framed<br />$225
						</p>
					</div>
					<div class="col-sm-6">
						<a href="#" data-lightbox="img/Strata_ll.jpg" data-frame="dark-lb"><img src="img/Strata_ll.jpg" class="center-block landscape" alt="Strata II" /></a>
						<h3 class=" text-center mg-sm">
							Strata II
						</h3>
						<p class=" text-center">
							8" x 11", framed<br />$225
						</p>
					</div>
				</div>
				<div class="row row-move-down">
					<div class="col-sm-4">
						<a href="#" data-lightbox="img/Alstroemeria.jpg" data-frame="dark-lb"><img src="img/Alstroemeria.jpg" class="center-block portrait" alt="Alstroemeria" /></a>
						<h3 class=" text-center mg-sm">
							Alstroemeria
						</h3>
						<p class=" text-center">
							8" x 11", framed<br />$225
						</p>
					</div>
					<div class="col-sm-4">
						<a href="#" data-lightbox="img/Tulip_Bouquet.jpg" data-frame="dark-lb"><img src="img/Tulip_Bouquet.jpg" class="center-block portrait" alt="Tulip Bouquet" /></a>
						<h3 class=" text-center mg-sm">
							Tulip Bouquet
						</h3>
						<p class=" text-center">
							8" x 11", framed<br />$225
						</p>
					</div>
					<div class="col-sm-4">
						<a href="#" data-lightbox="img/Red_Tulips.jpg" data-frame="dark-lb"><img src="img/Red_Tulips.jpg" class="center-block portrait" alt="Red Tulips" /></a>
						<h3 class=" text-center mg-sm">
							Red Tulips
						</h3>
						<p class=" text-center">
							8" x 11", framed<br />$225
						</p>
					</div>
				</div>
				<div class="row row-move-down">
					<div class="col-sm-12">
						<a href="#" data-lightbox="img/Ancient_Doors.jpg" data-frame="dark-lb"><img src="img/Ancient_Doors.jpg" class="center-block landscape hidden-sm hidden-md hidden-lg" alt="Ancient Doors" /></a>
						<a href="#" data-lightbox="img/Ancient_Doors.jpg" data-frame="dark-lb"><img src="img/Ancient_Doors.jpg" class="center-block hidden-xs" style="width: 680px" alt="Ancient Doors" /></a>
						<h3 class=" text-center mg-sm">
							Ancient Doors
						</h3>
						<p class=" text-center">
							32" x 16", framed<br />$475
						</p>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- bloc-exhibitions-watercolours END -->