<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>Lina Yachnin – Florals</title>
	<?php include 'source/meta_header.php';?>
	<meta property="og:title" content="Floral paintings by Lina Yachnin — Canadian Oil & Watercolour Artist"/>
</head>
<body>
<!-- Main container -->
<div class="page-container">

<?php include 'source/navbar.php';?>

<!-- bloc-florals-banner -->
<div class="bloc b-parallax bg-Bougainvillea bgc-white-2 l-bloc bg-l-edge banner" id="bloc-florals-banner">
	<div class="container bloc-lg">
		<div class="row">
			<div class="col-sm-12">
				<h1 class="mg-md tc-white-2 mm-links">
					<strong>Florals</strong>
				</h1>
			</div>
		</div>
	</div>
</div>
<!-- bloc-florals-banner END -->

<!-- bloc-florals-watercolours -->
<?php generate_paintings("watercolour", "paintings/florals_watercolours.csv", $curpage[0], "gainsboro");?>
<!-- bloc-florals-watercolours END -->

<!-- bloc-florals-oils -->
<?php generate_paintings("oil", "paintings/florals_oils.csv", $curpage[0]);?>
<!-- bloc-florals-oils END -->

<?php include 'source/social_footer.php';?>

</div>
<!-- Main container END -->

<?php include 'source/scripts_footer.php';?>
</body>

<!-- Google Analytics -->

<!-- Google Analytics END -->

</html>
