<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>Lina Yachnin – Florals</title>
	<?php include 'source/meta_header.php';?>
	<meta property="og:title" content="Floral paintings by Lina Yachnin — Canadian Oil & Watercolour Artist"/>
</head>
<body>
<!-- Main container -->
<div class="page-container">

<?php include 'source/navbar.php';?>

<!-- bloc-florals-banner -->
<div class="bloc b-parallax bg-Bougainvillea bgc-white-2 l-bloc bg-l-edge banner" id="bloc-florals-banner">
	<div class="container bloc-lg">
		<div class="row">
			<div class="col-sm-12">
				<h1 class="mg-md tc-white-2 mm-links">
					<strong>Florals</strong>
				</h1>
			</div>
		</div>
	</div>
</div>
<!-- bloc-florals-banner END -->

<!-- bloc-florals-watercolours -->
<div class="bloc bgc-white-2 l-bloc painting-text" id="bloc-florals-watercolours">
	<div class="container bloc-md">
		<div class="row">
			<div class="col-sm-12">
				<h2 class="text-center mg-md ">
					Watercolour
				</h2>
				<div class="divider-h">
					<span class="divider divider-half"></span>
				</div>
				<div class="row">
					<div class="col-sm-6">
						<a href="#" data-lightbox="img/Bouquet_in_Blue.jpg" data-frame="dark-lb"><img src="img/Bouquet_in_Blue.jpg" class="center-block portrait" alt="Bouquet in Blue" /></a>
						<h3 class=" text-center mg-sm">
							Bouquet in Blue
						</h3>
						<p class="text-center">
							11" x 14"<br/>
							Watercolour on paper, framed<br />
							$195
						</p>
					</div>
					<div class="col-sm-6">
						<a href="#" data-lightbox="img/Draped_in_Blue_II.jpg" data-frame="dark-lb"><img src="img/Draped_in_Blue_II.jpg" class="center-block portrait" alt="Draped in Blue II" /></a>
						<h3 class=" text-center mg-sm">
							Draped in Blue II
						</h3>
						<p class="text-center">
							19" x 29", framed<br/>
							$650
						</p>
					</div>
				</div>
				<div class="row row-move-down">
					<div class="col-sm-4">
						<a href="#" data-lightbox="img/Draped_in_Blue.jpg" data-frame="dark-lb"><img src="img/Draped_in_Blue.jpg" class="center-block portrait" alt="Draped in Blue" /></a>
						<h3 class=" text-center mg-sm">
							Draped in Blue (Sold)
						</h3>
					</div>
					<div class="col-sm-4">
						<a href="#" data-lightbox="img/Just_for_You.jpg" data-frame="dark-lb"><img src="img/Just_for_You.jpg" class="center-block portrait" alt="Just for You" /></a>
						<h3 class=" text-center mg-sm">
							Just for You (Sold)
						</h3>
					</div>
					<div class="col-sm-4">
						<a href="#" data-lightbox="img/Bouquet_with_Tulips.jpg" data-frame="dark-lb"><img src="img/Bouquet_with_Tulips.jpg" class="center-block portrait" alt="Bouquet with Tulips" /></a>
						<h3 class=" text-center mg-sm">
							Bouquet with Tulips (Sold)
						</h3>
					</div>
				</div>
				<div class="row row-move-down">
					<div class="col-sm-3">
						<a href="#" data-lightbox="img/Bouquet_II.jpg" data-frame="dark-lb"><img src="img/Bouquet_II.jpg" class="center-block portrait" alt="Bouquet II" /></a>
						<h3 class=" text-center mg-sm">
							Bouquet II (Sold)
						</h3>
					</div>
					<div class="col-sm-3">
						<a href="#" data-lightbox="img/Joyful_Distraction.jpg" data-frame="dark-lb"><img src="img/Joyful_Distraction.jpg" class="center-block portrait" alt="Joyful Distraction" /></a>
						<h3 class=" text-center mg-sm">
							Joyful Distraction (Sold)
						</h3>
					</div>
					<div class="col-sm-3">
						<a href="#" data-lightbox="img/Still_Life_with_Flowers.jpg" data-frame="dark-lb"><img src="img/Still_Life_with_Flowers.jpg" class="center-block portrait" alt="Still Life with Flowers" /></a>
						<h3 class=" text-center mg-sm">
							Still Life with Flowers (Sold)
						</h3>
					</div>
					<div class="col-sm-3">
						<a href="#" data-lightbox="img/Lilacs.jpg" data-frame="dark-lb"><img src="img/Lilacs.jpg" class="center-block portrait" alt="Lilacs" /></a>
						<h3 class=" text-center mg-sm">
							Lilacs (Sold)
						</h3>
					</div>
				</div>
				<div class="row row-move-down">
					<div class="col-sm-3">
						<a href="#" data-lightbox="img/Alstroemeria.jpg" data-frame="dark-lb"><img src="img/Alstroemeria.jpg" class="center-block portrait" alt="Alstroemeria" /></a>
						<h3 class=" text-center mg-sm">
							Alstroemeria (Sold)
						</h3>
					</div>
					<div class="col-sm-3">
						<a href="#" data-lightbox="img/Coquelicots.jpg" data-frame="dark-lb"><img src="img/Coquelicots.jpg" class="center-block portrait" alt="Coquelicots" /></a>
						<h3 class=" text-center mg-sm">
							Coquelicots (Sold)
						</h3>
					</div>
					<div class="col-sm-3">
						<a data-frame="dark-lb" data-lightbox="img/Tulip.jpg" href="#">
							<img alt="Tulip" class="center-block portrait" src="img/Tulip.jpg"/>
						</a>
						<h3 class="mg-sm  text-center">Tulip (Sold)</h3>
					</div>
					<div class="col-sm-3">
						<a href="#" data-lightbox="img/Tulip_Bouquet.jpg" data-frame="dark-lb"><img src="img/Tulip_Bouquet.jpg" class="center-block portrait" alt="Tulip Bouquet" /></a>
						<h3 class=" text-center mg-sm">
							Tulip Bouquet (Sold)
						</h3>
					</div>
				</div>
				<div class="row row-move-down">
					<div class="col-sm-3">
						<a href="#" data-lightbox="img/Red_Tulips.jpg" data-frame="dark-lb"><img src="img/Red_Tulips.jpg" class="center-block portrait" alt="Red Tulips" /></a>
						<h3 class=" text-center mg-sm">
							Red Tulips (Sold)
						</h3>
					</div>
					<div class="col-sm-3">
						<a href="#" data-lightbox="img/In_Bloom.jpg" data-frame="dark-lb"><img src="img/In_Bloom.jpg" class="center-block portrait" alt="In Bloom" /></a>
						<h3 class=" text-center mg-sm">
							In Bloom (Sold)
						</h3>
					</div>
					<div class="col-sm-3">
						<a href="#" data-lightbox="img/Bouquet.jpg" data-frame="dark-lb"><img src="img/Bouquet.jpg" class="center-block portrait" alt="Bouquet" /></a>
						<h3 class=" text-center mg-sm">
							Bouquet (Sold)
						</h3>
					</div>
					<div class="col-sm-3">
						<a href="#" data-lightbox="img/Summer_Bouquet.jpg" data-frame="dark-lb"><img src="img/Summer_Bouquet.jpg" class="center-block portrait" alt="Summer Bouquet" /></a>
						<h3 class=" text-center mg-sm">
							Summer Bouquet (Sold)
						</h3>
					</div>
				</div>
				<div class="row row-move-down">
					<div class="col-sm-3">
						<a href="#" data-lightbox="img/Tulips-watercolour.jpg" data-frame="dark-lb"><img src="img/Tulips-watercolour.jpg" class="center-block landscape" alt="Tulips" /></a>
						<h3 class=" text-center mg-sm">
							Tulips (Sold)
						</h3>
					</div>
					<div class="col-sm-3">
						<a href="#" data-lightbox="img/Trilliums_bckgrnd.jpg" data-frame="dark-lb"><img src="img/Trilliums_bckgrnd.jpg" class="center-block landscape" alt="Trilliums" /></a>
						<h3 class=" text-center mg-sm">
							Trilliums (Sold)
						</h3>
					</div>
					<div class="col-sm-3">
						<a href="#" data-lightbox="img/Ready_to_Eat.jpg" data-frame="dark-lb"><img src="img/Ready_to_Eat.jpg" class="center-block landscape" alt="Ready to Eat (sold)" /></a>
						<h3 class="mg-sm  text-center">
							Ready to Eat (Sold)
						</h3>
					</div>
					<div class="col-sm-3">
						<a href="#" data-lightbox="img/Wild_Flowers.jpg" data-frame="dark-lb"><img src="img/Wild_Flowers.jpg" class="center-block landscape" alt="Wildflowers (sold)" /></a>
						<h3 class="mg-sm  text-center">
							Wild Flowers (Sold)
						</h3>
					</div>
				</div>
				<div class="row row-move-down">
					<div class="col-sm-3">
						<a href="#" data-lightbox="img/Magnolias.jpg" data-frame="dark-lb"><img src="img/Magnolias.jpg" class="center-block portrait" alt="Magnolias (sold)" /></a>
						<h3 class=" text-center mg-sm">
							Magnolias (Sold)
						</h3>
					</div>
					<div class="col-sm-3">
						<a href="#" data-lightbox="img/Just_Tulips.jpg" data-frame="dark-lb"><img src="img/Just_Tulips.jpg" class="center-block portrait" alt="Just Tulips (sold)" /></a>
						<h3 class="mg-sm  text-center">
							Just Tulips (Sold)
						</h3>
					</div>
					<div class="col-sm-3">
						<a data-lightbox="img/Hydrangeas-_and_Thyme.jpg" data-frame="dark-lb" href="#"><img src="img/Hydrangeas-_and_Thyme.jpg" class="center-block portrait" alt="Hydrangeas and Thyme (sold)" /></a>
						<h3 class="mg-sm  text-center">
							Hydrangeas & Thyme (Sold)
						</h3>
					</div>
					<div class="col-sm-3">
						<a href="#" data-lightbox="img/Tulips_Bottles_and_Tangerines.jpg" data-frame="dark-lb"><img src="img/Tulips_Bottles_and_Tangerines.jpg" class="center-block portrait" alt="Tulips & Tangerines (sold)" /></a>
						<h3 class="mg-sm  text-center">
							Tulips & Tangerines (Sold)
						</h3>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- bloc-florals-watercolours END -->

<!-- bloc-florals-oils -->
<div class="bloc bgc-gainsboro l-bloc painting-text" id="bloc-florals-oils">
	<div class="container bloc-md">
		<div class="row">
			<div class="col-sm-12">
				<h2 class="text-center mg-md ">
					Oil
				</h2>
				<div class="divider-h">
					<span class="divider divider-half"></span>
				</div>

				<div class="row">
					<div class="col-sm-3">
						<a href="#" data-lightbox="img/Daffodils_in_the_Wind.jpg" data-frame="dark-lb"><img src="img/Daffodils_in_the_Wind.jpg" class="center-block landscape" alt="Daffodils in the Wind" /></a>
						<h3 class="mg-sm  text-center">
							Daffodils in the Wind (Sold)
						</h3>
						<!-- <p class=" text-center">$400, framed<br />12" x 24"</p> -->
					</div>
					<div class="col-sm-3">
						<a href="#" data-lightbox="img/Tulips.jpg" data-frame="dark-lb"><img src="img/Tulips.jpg" class="center-block landscape" alt="Tulips (sold)" /></a>
						<h3 class="mg-sm  text-center">
							Tulips (Sold)
						</h3>
					</div>
					<div class="col-sm-3">
						<a href="#" data-lightbox="img/Bougainvillea.jpg" data-frame="dark-lb"><img src="img/Bougainvillea.jpg" class="center-block landscape" alt="Bougainvillea (sold)" /></a>
						<h3 class="mg-sm  text-center">
							Bougainvillea (Sold)
						</h3>
					</div>
					<div class="col-sm-3">
						<a href="#" data-lightbox="img/Grasses.jpg" data-frame="dark-lb"><img src="img/Grasses.jpg" class="center-block landscape" alt="Grasses (sold)" /></a>
						<h3 class="mg-sm  text-center">
							Grasses (Sold)
						</h3>
					</div>
				</div>
				<div class="row row-move-down">
					<div class="col-sm-3">
						<a href="#" data-lightbox="img/Daffodils.jpg" data-frame="dark-lb"><img src="img/Daffodils.jpg" class="center-block landscape" alt="Daffodils (sold)" /></a>
						<h3 class="mg-sm  text-center">
							Daffodils (Sold)
						</h3>
					</div>
					<div class="col-sm-3">
						<a href="#" data-lightbox="img/Poppies.jpg" data-frame="dark-lb"><img src="img/Poppies.jpg" class="center-block portrait" alt="Poppies (sold)" /></a>
						<h3 class="mg-sm  text-center">
							Poppies (Sold)
						</h3>
					</div>
					<div class="col-sm-3">
						<a href="#" data-lightbox="img/Wildflowers.jpg" data-frame="dark-lb"><img src="img/Wildflowers.jpg" class="center-block landscape" alt="Wildflowers (sold)" /></a>
						<h3 class="mg-sm  text-center">
							Wildflowers (Sold)
						</h3>
					</div>
					<div class="col-sm-3">
						<a href="#" data-lightbox="img/Field_of_Irises.jpg" data-frame="dark-lb"><img src="img/Field_of_Irises.jpg" class="center-block landscape" alt="Field of Irises (sold)" /></a>
						<h3 class="mg-sm  text-center">
							Field of Irises (Sold)
						</h3>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- bloc-florals-oils END -->

<?php include 'source/social_footer.php';?>

</div>
<!-- Main container END -->

<?php include 'source/scripts_footer.php';?>
</body>

<!-- Google Analytics -->

<!-- Google Analytics END -->

</html>
