<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Lina Yachnin – Canadian Oil & Watercolour Artist</title>
	<?php include 'source/meta_header.php';?>
	<meta property="og:title" content="Lina Yachnin — Canadian Oil & Watercolour Artist">
	<meta name="google-site-verification" content="CLdh5ywAsuIr9fi0_8p9eE3seI0VBYniQX0G_Lx4VTw">
	<link rel="canonical" href="https://www.linayachnin.com">
</head>
<body>
<!-- Main container -->
<div class="page-container">
<!-- This is the spinning wheel load graphic, which will disappear after page load -->
<div id="page-loading-blocs-notifaction" class="bloc-fill-screen"></div>
<!-- Spinning wheel load graphic END -->

<!-- bloc-navbar-mobile -->
<div class="bloc hidden-sm hidden-lg hidden-md bgc-navbar l-bloc" id="bloc-navbar-mobile">
	<div class="container">
		<nav class="navbar row">
			<div class="navbar-header">
				<a href="https://www.instagram.com/linayachnin/" class="icon-padding" target="_blank"><span class="fa fa-instagram icon-md pull-left"></span></a>
				<a href="https://www.linkedin.com/in/lina-yachnin-54a9a28a" target="_blank"><span class="fa fa-linkedin icon-md pull-left"></span></a>
				<button id="nav-toggle" type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-1">
					<span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
				</button>
			</div>
			<div class="navbar-collapse navbar-1 collapse">
				<ul class="site-navigation nav navbar-nav list-dimensions">
					<li>
						<a href="index">Home</a>
					</li>
					<li>
						<a href="exhibitions"><?php echo $ex_title;?></a>
					</li>
					<li>
						<a href="about">About</a>
					</li>
					<li>
						<a href="florals">Florals</a>
					</li>
					<li>
						<a href="landscapes">Landscapes</a>
					</li>
					<li>
						<a href="abstracts">Abstracts</a>
					</li>
					<li>
						<a href="urbanscapes">Urbanscapes</a>
					</li>
					<li>
						<a href="contact">Contact</a>
					</li>
				</ul>
			</div>
		</nav>
	</div>
</div>
<!-- bloc-navbar-mobile END -->

<!-- bloc-index-titlebanner-desktop -->
<div class="bloc hidden-xs bgc-main-bg" id="bloc-index-titlebanner-desktop">
	<div class="container">
		<div class="row">
			<div class="col-sm-12">
				<a href="index"><img src="img/Lina_yachnin_signature_big.jpg" class="img-responsive mg-md center-block sig-mainmenu" width="700" alt="Lina Yachnin"></a>
				<h2 class=" mg-sm-sm subtitle text-center mg-sm">
					Canadian Oil &amp; Watercolour Artist
				</h2>
				<div class="divider-h">
					<span class="divider-half"></span>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- bloc-index-titlebanner-desktop END -->

<!-- bloc-index-titlebanner-mobile -->
<div class="bloc hidden-lg hidden-md hidden-sm bgc-main-bg" id="bloc-index-titlebanner-mobile">
	<div class="container bloc-sm">
		<div class="row">
			<div class="col-sm-12">
				<a href="index"><img src="img/Lina_yachnin_signature_big.jpg" class="img-responsive center-block mg-sm" width="843" alt="Lina Yachnin"></a>
				<h3 class=" mg-sm-sm subtitle text-center mg-sm mg-clear-xs text-w-80">
					Canadian Oil &amp; Watercolour Artist
				</h3>
			</div>
		</div>
	</div>
</div>
<!-- bloc-index-titlebanner-mobile END -->

<!-- bloc-navbar-index-desktop -->
<div class="bloc hidden-xs bgc-main-bg l-bloc" id="bloc-navbar-index-desktop">
	<div class="container">
		<nav class="navbar nav-center row">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-1">
					<span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
				</button>
			</div>
			<div class="navbar-collapse navbar-1 collapse">
				<ul class="site-navigation nav navbar-nav hidden-xs">
					<li>
						<a href="index">Home</a>
					</li>
					<li>
						<a href="exhibitions">Exhibitions</a>
					</li>
					<li>
						<a href="about">About</a>
					</li>
					<li>
						<a href="contact">Contact</a>
					</li>
				</ul>
			</div>
		</nav>
	</div>
</div>
<!-- bloc-navbar-index-desktop END -->

<!-- bloc-index-announcement -->
<div class="bloc bg-center l-bloc <?php if ((!$announcement)) {echo 'hidden-all';}?>" id="bloc-index-announcement">
	<div class="container">
		<div class="row">
			<div class="col-sm-12">
				<a class="center-block text-center hidden-sm hidden-md hidden-lg <?php if ($hide_announce_img) {echo 'hidden-all';}?>">
					<img class="portrait" src="<?php echo $announcement_img?>" alt="Announcement Image">
				</a>
				<a class="center-block hidden-xs <?php if ($hide_announce_img) {echo 'hidden-all';}?>" style="width: 588px" <?php if ($exhibition) {echo 'href="exhibitions"';}?>>
					<img src="<?php echo $announcement_img?>" alt="Announcement Image" style="width: 588px">
				</a>
				<br>
				<h3 class="text-center mg-sm">
					<?php echo $announcement_text;?>
				</h3>
			</div>
		</div>
	</div>
</div>
<!-- bloc-index-announcement END -->

<?php
	if ( $exhibition ) {
			include 'exhibitions_index.phtml';
		}
?>

<div class="divider-h">
	<span class="divider divider-half"></span>
</div>

<!-- bloc-index-availableworks -->
<div class="" id="bloc-index-availableworks">
	<div class="container">
		<div class="row">
			<div class="col-sm-3"></div>
			<div class="col-sm-6 button-link bgc-avail-works">
				<h2 class="mg-md">
					<a class="button-link" href="available_works"><i>Available Works</i></a>
				</h2>
			</div>
			<div class="col-sm-3"></div>
		</div>
	</div>
</div>
<!-- bloc-index-availableworks END -->

<!-- bloc-index-florals-mobile -->
<div class="bloc hidden-lg hidden-md hidden-sm b-parallax bg-Bougainvillea bgc-main-bg l-bloc bg-center" id="bloc-index-florals-mobile">
	<div class="container bloc-lg">
		<div class="row">
			<div class="col-sm-12">
				<h2><a class="pull-left tc-white mm-links-mobile" href="florals">Florals</a></h2>
			</div>
		</div>
	</div>
</div>
<!-- bloc-index-florals-mobile END -->

<!-- spacer -->
<div class="bloc hidden-lg hidden-md hidden-sm bgc-accent-bg l-bloc bloc-width">
	<div class="container">
		<div class="row">
			<div class="col-sm-12">
			</div>
		</div>
	</div>
</div>
<!-- spacer END -->

<!-- bloc-index-landscapes-mobile -->
<div class="bloc hidden-lg hidden-md hidden-sm bgc-main-bg bg-Through-the-Trees l-bloc b-parallax bg-center" id="bloc-index-landscapes-mobile">
	<div class="container bloc-lg">
		<div class="row">
			<div class="col-sm-12">
				<a class="pull-left mm-links-mobile tc-white" href="landscapes">Landscapes</a>
			</div>
		</div>
	</div>
</div>
<!-- bloc-index-landscapes-mobile END -->

<!-- spacer -->
<div class="bloc hidden-lg hidden-md hidden-sm bgc-accent-bg l-bloc bloc-width">
	<div class="container">
		<div class="row">
			<div class="col-sm-12">
			</div>
		</div>
	</div>
</div>
<!-- spacer END -->

<!-- bloc-index-abstracts-mobile -->
<div class="bloc bgc-main-bg hidden-lg hidden-md hidden-sm b-parallax bg-Airport-Reflections l-bloc bg-center" id="bloc-index-abstracts-mobile">
	<div class="container bloc-lg">
		<div class="row">
			<div class="col-sm-12">
				<a class="pull-left mm-links-mobile tc-white" href="abstracts">Abstracts</a>
			</div>
		</div>
	</div>
</div>
<!-- bloc-index-abstracts-mobile END -->

<!-- spacer -->
<div class="bloc hidden-lg hidden-md hidden-sm bgc-accent-bg l-bloc bloc-width">
	<div class="container">
		<div class="row">
			<div class="col-sm-12">
			</div>
		</div>
	</div>
</div>
<!-- spacer END -->

<!-- bloc-index-urbanscapes-mobile -->
<div class="bloc bgc-main-bg hidden-lg hidden-md hidden-sm b-parallax bg-Portbou l-bloc bg-center" id="bloc-index-urbanscapes-mobile">
	<div class="container bloc-lg">
		<div class="row">
			<div class="col-sm-12">
				<a class="pull-left mm-links-mobile tc-white" href="urbanscapes">Urbanscapes</a>
			</div>
		</div>
	</div>
</div>
<!-- bloc-index-urbanscapes-mobile END -->

<!-- Bloc Group -->

<div class="hidden-xs divider-h">
	<span class="divider divider-half"></span>
</div>

<div class='bloc-group'>

<!-- bloc-index-florals-desktop -->
<div class="bloc bloc-tile-4 hidden-xs bg-poppies-back2 l-bloc" id="bloc-index-florals-desktop">
	<div class="container bloc-md">
		<div class="row">
			<div class="col-sm-12 no-horiz-padding">
				<h2 class="mg-md text-left  text-right">
					<a class="over-image-title-text tc-white" href="florals">Florals</a>
				</h2>
			</div>
		</div>
	</div>
</div>
<!-- bloc-index-florals-desktop END -->

<!-- bloc-index-landscapes-desktop -->
<div class="bloc bloc-tile-4 hidden-xs bg-coastalsky-back2 l-bloc" id="bloc-index-landscapes-desktop">
	<div class="container bloc-md">
		<div class="row">
			<div class="col-sm-12 no-horiz-padding">
				<h2 class="mg-md text-left  text-center tc-white over-image-title-text">
					<a class="over-image-title-text tc-white" href="landscapes">Landscapes</a>
				</h2>
			</div>
		</div>
	</div>
</div>
<!-- bloc-index-landscapes-desktop END -->

<!-- bloc-index-abstracts-desktop -->
<div class="bloc bloc-tile-4 hidden-xs bg-Airport-Reflections-back2 l-bloc" id="bloc-index-abstracts-desktop">
	<div class="container bloc-md">
		<div class="row">
			<div class="col-sm-12 no-horiz-padding">
				<h2 class="mg-md  text-left tc-white over-image-title-text">
					<a class="over-image-title-text tc-white" href="abstracts">Abstracts</a>
				</h2>
			</div>
		</div>
	</div>
</div>
<!-- bloc-index-abstracts-desktop END -->

<!-- bloc-index-urbanscapes-desktop -->
<div class="bloc bloc-tile-4 hidden-xs bg-Portbou l-bloc" id="bloc-index-urbanscapes-desktop">
	<div class="container bloc-md">
		<div class="row">
			<div class="col-sm-12 no-horiz-padding">
				<h2 class="mg-md  text-left tc-white over-image-title-text">
					<a class="over-image-title-text tc-white" href="urbanscapes">Urbanscapes</a>
				</h2>
			</div>
		</div>
	</div>
</div>
<!-- bloc-index-abstracts-desktop END -->
</div>
<!-- Bloc Group END -->

<?php include 'source/social_footer.php';?>

</div>
<!-- Main container END -->

<?php include 'source/scripts_footer.php';?>
</body>

<!-- Google Analytics -->

<!-- Google Analytics END -->

</html>
