<!doctype html>
<html>
<head>
	<meta charset="utf-8">
	<title>Lina Yachnin &ndash; Landscapes</title>
	<?php include 'source/meta_header.php';?>
	<meta property="og:title" content="Landscape paintings by Lina Yachnin — Canadian Oil & Watercolour Artist"/>
</head>
<body><!-- Main container -->
<div class="page-container">

<?php include 'source/navbar.php';?>

<!-- bloc-landscapes-banner -->
<div class="bloc b-parallax bgc-white-2 bg-Coastal-Sky-III-bckgrnd l-bloc bg-l-edge banner" id="bloc-landscapes-banner">
	<div class="container bloc-lg">
		<div class="row">
			<div class="col-sm-12">
				<h1 class="mg-md mm-links tc-white-2">
					<strong>Landscapes</strong>
				</h1>
			</div>
		</div>
	</div>
</div>
<!-- bloc-landscapes-banner END -->

<!-- bloc-landscapes-watercolours -->
<div class="bloc bgc-white-2 l-bloc painting-text" id="bloc-landscapes-watercolours">
	<div class="container bloc-sm">
		<div class="row">
			<div class="col-sm-12">
				<h2 class="text-center mg-md ">Watercolour</h2>

				<div class="divider-h">
					<span class="divider divider-half"></span>
				</div>
				
				<div class="row">
					<div class="col-sm-6">
						<a data-frame="dark-lb" data-lightbox="img/Storm_Approaching.jpg" href="#">
							<img alt="Storm Approaching" class="center-block landscape" src="img/Storm_Approaching.jpg"/>
						</a>
						<h3 class="mg-sm  text-center">Storm Approaching</h3>
						<p class="text-center">8" x 10", framed<br />$150</p>
					</div>
					<div class="col-sm-6">
						<a data-frame="dark-lb" data-lightbox="img/Tom-Thompson-Sunset-5x7-Card.jpg" href="#">
							<img class="center-block landscape" src="img/Tom-Thompson-Sunset-5x7-Card.jpg" alt="Tom Thompson Sunset"/>
						</a>
						<h3 class="mg-sm text-center">Tom Thompson Sunset (Sold)</h3>
					</div>
				</div>

				<div class="row row-move-down">
					<div class="col-sm-3">
						<a href="#" data-lightbox="img/After_the_Storm.jpg" data-frame="dark-lb"><img src="img/After_the_Storm.jpg" class="center-block portrait" alt="After the Storm" /></a>
						<h3 class=" text-center mg-sm">
							After the Storm (Sold)
						</h3>
					</div>
					<div class="col-sm-3">
						<a href="#" data-lightbox="img/After_the_Storm_2.jpg" data-frame="dark-lb"><img src="img/After_the_Storm_2.jpg" class="center-block portrait" alt="After the Storm 2" /></a>
						<h3 class=" text-center mg-sm">
							After the Storm (Sold)
						</h3>
					</div>
					<div class="col-sm-3">
						<a data-frame="dark-lb" data-lightbox="img/Storm_Leaving_Mer-Bleue.jpg" href="#">
							<img alt="Storm Leaving, Mer Bleue (Sold)" class="center-block portrait" src="img/Storm_Leaving_Mer-Bleue.jpg"/>
						</a>

						<h3 class="mg-sm  text-center">Storm Leaving, Mer Bleue (Sold)</h3>
					</div>
					<div class="col-sm-3">
						<a data-frame="dark-lb" data-lightbox="img/Mountain_Reflections_2.jpg" href="#">
							<img alt="Mountain Reflections (Sold)" class="center-block portrait" src="img/Mountain_Reflections_2.jpg"/>
						</a>
						<h3 class="mg-sm  text-center">Mountain Reflections (Sold)</h3>
					</div>
				</div>

				<div class="row row-move-down">
					<div class="col-sm-3">
						<a data-frame="dark-lb" data-lightbox="img/Storm_Leaving_comma_Charlevoix.jpg" href="#">
							<img alt="Storm Leaving, Charlevoix (Sold)" class="center-block landscape" src="img/Storm_Leaving_comma_Charlevoix.jpg"/>
						</a>
						<h3 class="mg-sm  text-center">Storm Leaving, Charlevoix (Sold)</h3>
					</div>

					<div class="col-sm-3">
						<div class="text-center">
							<a data-frame="dark-lb" data-lightbox="img/Meech-Lake-5x7-Card.jpg" href="#">
								<img alt="Meech Lake (sold)" class="center-block landscape" src="img/Meech-Lake-5x7-Card.jpg"/>
							</a>
						</div>
						<h3 class="text-center mg-sm">Meech Lake (Sold)</h3>
					</div>

					<div class="col-sm-3">
						<a data-frame="dark-lb" data-lightbox="img/Mountain_Reflections.jpg" href="#">
							<img alt="Mountain Reflections (Sold)" class="center-block landscape" src="img/Mountain_Reflections.jpg"/>
						</a>
						<h3 class="mg-sm  text-center">Mountain Reflections (Sold)</h3>
					</div>

					<div class="col-sm-3">
						<a data-frame="dark-lb" data-lightbox="img/40_Below_at_Shilly_Shally.jpg" href="#">
							<img alt="40 Below At Shilly Shally" class="center-block landscape" src="img/40_Below_at_Shilly_Shally.jpg"/>
						</a>
						<h3 class="text-center mg-sm">40 Below At Shilly Shally (Sold)</h3>
					</div>
				</div>
			</div>
		</div>	
	</div>
</div>
<!-- bloc-landscapes-watercolours END -->

<!-- bloc-landscapes-oils -->
<div class="bloc bgc-gainsboro l-bloc painting-text" id="bloc-landscapes-oils">
	<div class="container bloc-md">
		<div class="row">
			<div class="col-sm-12">
				<h2 class="text-center mg-md ">Oil</h2>

				<div class="divider-h">
					<span class="divider divider-half"></span>
				</div>

				<div class="row">
					<div class="col-sm-3">
						<a data-frame="dark-lb" data-lightbox="img/Sunset_Through_the_Trees_2.jpg" href="#">
							<img alt="Sunset Through the Trees" class="center-block landscape" src="img/Sunset_Through_the_Trees_2.jpg"/>
						</a>
						<h3 class="mg-sm  text-center">Sunset Through the Trees</h3>
						<p class="text-center">12" x 12" each<br/>$200 each or 2 for $375<br/>Oil on gallery canvas</p>
					</div>
					<div class="col-sm-3">
						<a data-frame="dark-lb" data-lightbox="img/Huron.jpg" href="#">
							<img alt="Huron" class="center-block landscape" src="img/Huron.jpg"/>
						</a>
						<h3 class="mg-sm  text-center">Huron</h3>
						<p class="text-center">10" x 10", oil on canvas<br />$180</p>
					</div>
					<div class="col-sm-3">
						<a data-frame="dark-lb" data-lightbox="img/Huron_Shadows.jpg" href="#">
							<img alt="Huron Shadows" class="center-block landscape" src="img/Huron_Shadows.jpg"/>
						</a>
						<h3 class="mg-sm  text-center">Huron Shadows</h3>
						<p class="text-center">10" x 10", oil on gallery canvas<br />$180</p>
					</div>
					<div class="col-sm-3">
						<a data-frame="dark-lb" data-lightbox="img/Homeward_2.jpg" href="#">
							<img alt="Homeward 2" class="center-block landscape" src="img/Homeward_2.jpg"/>
						</a>
						<h3 class="mg-sm  text-center">Homeward 2</h3>
						<p class="text-center">12" x 18", oil on gallery canvas<br />$275</p>
					</div>
				</div>
				
				<div class="row row-move-down">
					<div class="col-sm-4">
						<a data-frame="dark-lb" data-lightbox="img/Coastal_Sunset.jpg" href="#">
							<img alt="Coastal Sunset" class="center-block portrait" src="img/Coastal_Sunset.jpg"/>
						</a>

						<h3 class="mg-sm  text-center">Coastal Sunset</h3>
						<p class="text-center">24" x 48", framed<br />$1,100</p>
					</div>
					<div class="col-sm-4">
						<a data-frame="dark-lb" data-lightbox="img/Winter_Shadows.jpg" href="#">
							<img alt="Winter Shadows" class="center-block portrait" src="img/Winter_Shadows.jpg"/>
						</a>

						<h3 class="mg-sm  text-center">Winter Shadows</h3>
						<p class="text-center">10" x 20", oil on gallery canvas<br />$295</p>
					</div>
					<div class="col-sm-4">
						<a data-frame="dark-lb" data-lightbox="img/Blue_Wax_Day.jpg" href="#">
							<img alt="Blue Wax Day" class="center-block portrait" src="img/Blue_Wax_Day.jpg"/>
						</a>
						<h3 class="mg-sm  text-center">Blue Wax Day</h3>
						<p class="text-center">10" x 20", oil on gallery canvas<br />$295</p>
					</div>
				</div>
				
				<div class="row row-move-down">
					<div class="col-sm-4">
						<a href="#" data-lightbox="img/Autumn_Through_the_Trees.jpg" data-frame="dark-lb"><img src="img/Autumn_Through_the_Trees.jpg" class="center-block landscape" alt="Autumn Through the Trees" /></a>
						<h3 class="mg-sm  text-center">
							Autumn Through the Trees
						</h3>
						<p class=" text-center">24" x 24", oil on gallery canvas<br />$550</p>
					</div>
					<div class="col-sm-4">
						<a href="#" data-lightbox="img/Sundown_20170912.jpg" data-frame="dark-lb"><img src="img/Sundown_20170912.jpg" class="center-block landscape" alt="Sundown" /></a>
						<h3 class="mg-sm  text-center">
							Sundown (Sold)
						</h3>
					</div>
					<div class="col-sm-4">
						<a href="#" data-lightbox="img/Homeward.jpg" data-frame="dark-lb"><img src="img/Homeward.jpg" class="center-block landscape" alt="Homeward" /></a>
						<h3 class="mg-sm  text-center">
							Homeward (Sold)
						</h3>
					</div>
				</div>
				
				<div class="row row-move-down">
					<div class="col-sm-4">
						<a data-frame="dark-lb" data-lightbox="img/Movement.jpg" href="#">
							<img alt="Fall Reflections" class="center-block portrait" src="img/Fall_Reflections.jpg"/>
						</a>
						<h3 class="mg-sm  text-center">Fall Reflections (Sold)</h3>
					</div>

					<div class="col-sm-4">
						<a data-frame="dark-lb" data-lightbox="img/Coastal_Sky_III.jpg" href="#">
							<img alt="Fall Storm Leaving" class="center-block portrait" src="img/Coastal_Sky_III.jpg"/>
						</a>

						<h3 class="mg-sm  text-center">Fall Storm Leaving (Sold)</h3>
					</div>

					<div class="col-sm-4">
						<a data-frame="dark-lb" data-lightbox="img/Big-Sky.jpg" href="#">
							<img alt="Big Sky" class="center-block portrait" src="img/Big-Sky.jpg"/>
						</a>
						<h3 class="mg-sm  text-center">Big Sky (Sold)</h3>
					</div>
				</div>

				<div class="row row-move-down">
					<div class="col-sm-4">
						<a data-frame="dark-lb" data-lightbox="img/First-Ski.jpg" href="#">
							<img alt="First Ski (sold)" class="center-block portrait" src="img/First-Ski.jpg"/>
						</a>
						<h3 class="mg-sm  text-center">First Ski (Sold)</h3>
					</div>

					<div class="col-sm-4">
						<a data-frame="dark-lb" data-lightbox="img/Chelsea_Morning.jpg" href="#">
							<img alt="Chelsea Morning (Sold)" class="center-block portrait" src="img/Chelsea_Morning.jpg"/>
						</a>
						<h3 class="mg-sm  text-center">Chelsea Morning (Sold)</h3>
					</div>

					<div class="col-sm-4">
						<a data-frame="dark-lb" data-lightbox="img/Coastal_Sky.jpg" href="#">
							<img alt="Coastal Sky (Sold)" class="center-block portrait" src="img/Coastal_Sky.jpg"/>
						</a>
						<h3 class="mg-sm  text-center">Coastal Sky (Sold)</h3>
					</div>
				</div>

				<div class="row row-move-down">
					<div class="col-sm-3">
						<a data-frame="dark-lb" data-lightbox="img/Ottawa_River_Through_The_Trees.jpg" href="#">
							<img alt="Ottawa River, Through the Trees (Sold)" class="center-block landscape" src="img/Ottawa_River_Through_The_Trees.jpg"/>
						</a>
						<h3 class="mg-sm  text-center">Ottawa River, Through the Trees (Sold)</h3>
					</div>

					<div class="col-sm-3">
						<a data-frame="dark-lb" data-lightbox="img/Through_the_Trees_3.jpg" href="#">
							<img alt="Through the Trees (Sold)" class="center-block landscape" src="img/Through_the_Trees_3.jpg"/>
						</a>
						<h3 class="mg-sm  text-center">Through the Trees (Sold)</h3>
					</div>

					<div class="col-sm-3">
						<a data-frame="dark-lb" data-lightbox="img/Sunrise.jpg" href="#">
							<img alt="Sunrise (Sold)" class="center-block landscape" src="img/Sunrise.jpg"/>
						</a>
						<h3 class="mg-sm  text-center">Sunrise (Sold)</h3>
					</div>

					<div class="col-sm-3">
						<a data-frame="dark-lb" data-lightbox="img/Winter_Light.jpg" href="#">
							<img alt="Winter Light (Sold)" class="center-block landscape" src="img/Winter_Light.jpg"/>
						</a>
						<h3 class="mg-sm  text-center">Winter Light (Sold)</h3>
					</div>
				</div>

				<div class="row row-move-down">
					<div class="col-sm-3">
						<a data-frame="dark-lb" data-lightbox="img/The_November_Landscape.jpg" href="#">
							<img alt="The November Landscape (Sold)" class="center-block landscape" src="img/The_November_Landscape.jpg"/>
						</a>
						<h3 class="mg-sm  text-center">The November Landscape (Sold)</h3>
					</div>

					<div class="col-sm-3">
						<a data-frame="dark-lb" data-lightbox="img/View_of_the_Ottawa_River.jpg" href="#">
							<img alt="View of the Ottawa River (Sold)" class="center-block landscape" src="img/View_of_the_Ottawa_River.jpg"/>
						</a>
						<h3 class="mg-sm  text-center">View of the Ottawa River (Sold)</h3>
					</div>

					<div class="col-sm-3">
						<a data-frame="dark-lb" data-lightbox="img/Grand_Canyon.jpg" href="#">
							<img alt="Grand Canyon" class="center-block landscape" src="img/Grand_Canyon.jpg"/>
						</a>
						<h3 class="mg-sm  text-center">Grand Canyon (Sold)</h3>
					</div>

					<div class="col-sm-3">
						<a data-frame="dark-lb" data-lightbox="img/Greenstone_Trail_NZ.jpg" href="#">
							<img alt="Greenstone Trail, New Zealand (Sold)" class="center-block landscape" src="img/Greenstone_Trail_NZ.jpg"/>
						</a>

						<h3 class="mg-sm  text-center">Greenstone Trail, New Zealand (Sold)</h3>
					</div>
				</div>

				<div class="row row-move-down">
					<div class="col-sm-4">
						<a data-frame="dark-lb" data-lightbox="img/The_Trees_Around_You_2.jpg" href="#">
							<img alt="The Trees Around You II (Sold)" class="center-block landscape" src="img/The_Trees_Around_You_2.jpg"/>
						</a>
						<h3 class="mg-sm  text-center">The Trees Around You II (Sold)</h3>
					</div>
					<div class="col-sm-4">
						<a data-frame="dark-lb" data-lightbox="img/Late_Afternoon_Surf_1.jpg" href="#">
							<img alt="Late Afternoon Surf (Sold)" class="center-block landscape" src="img/Late_Afternoon_Surf_1.jpg"/>
						</a>
						<h3 class="mg-sm  text-center">Late Afternoon Surf (Sold)</h3>
					</div>

					<div class="col-sm-4">
						<a data-frame="dark-lb" data-lightbox="img/Winter_Stream_Gatineau.jpg" href="#">
							<img alt="Winter Stream, Gatineau (Sold)" class="center-block landscape" src="img/Winter_Stream_Gatineau.jpg"/>
						</a>
						<h3 class="mg-sm  text-center">Winter Stream, Gatineau (Sold)</h3>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- bloc-landscapes-oils END -->

<?php include 'source/social_footer.php';?>

</div>
<!-- Main container END --></body>
<!-- Google Analytics --><!-- Google Analytics END --></html>