<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>Lina Yachnin – Landscapes</title>
	<?php include 'source/meta_header.php';?>
	<meta property="og:title" content="Landscape paintings by Lina Yachnin — Canadian Oil & Watercolour Artist">
	<?php structured_data_from_csv(array("paintings/landscapes_watercolours.csv", "paintings/landscapes_oils.csv"));?>
</head>
<body><!-- Main container -->
<div class="page-container">

<?php include 'source/navbar.php';?>

<!-- bloc-landscapes-banner -->
<div class="bloc b-parallax bg-Coastal-Sky-III-bckgrnd bg-l-edge banner" id="bloc-landscapes-banner">
	<div class="container bloc-lg">
		<div class="row">
			<div class="col-sm-12">
				<h1 class="mg-md over-image-title-text tc-white-2">
					<strong>Landscapes</strong>
				</h1>
			</div>
		</div>
	</div>
</div>
<!-- bloc-landscapes-banner END -->

<!-- bloc-landscapes-watercolours -->
<?php generate_paintings("watercolour", "paintings/landscapes_watercolours.csv", $curpage[0], "accent-bg");?>
<!-- bloc-landscapes-watercolours END -->

<!-- bloc-landscapes-oils -->
<?php generate_paintings("oil", "paintings/landscapes_oils.csv", $curpage[0]);?>
<!-- bloc-landscapes-oils END -->

<?php include 'source/social_footer.php';?>

</div>
<?php include 'source/scripts_footer.php';?>
<!-- Main container END --></body>
<!-- Google Analytics --><!-- Google Analytics END --></html>