<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>Lina Yachnin – Urbanscapes</title>
	<?php include 'source/meta_header.php';?>
	<meta property="og:title" content="Urbanscape paintings by Lina Yachnin — Canadian Oil & Watercolour Artist"/>
</head>
<body>
<!-- Main container -->
<div class="page-container">
    
<?php include 'source/navbar.php';?>

<!-- bloc-urbanscape-banner -->
<div class="bloc bg-Portbou bgc-main-bg l-bloc b-parallax bg-center banner" id="bloc-urbanscape-banner">
	<div class="container bloc-lg">
		<div class="row">
			<div class="col-sm-12">
				<h1 class="mg-md tc-white mm-links">
					<strong>Urbanscapes</strong>
				</h1>
			</div>
		</div>
	</div>
</div>
<!-- bloc-urbanscape-banner END -->

<!-- bloc-urbanscapes-oils -->
<div class="bloc bgc-main-bg l-bloc painting-text hidden-all" id="bloc-urbanscapes-oils">
	<div class="container bloc-md">
		<div class="row">
			<div class="col-sm-12">
				<h2 class="text-center mg-md ">
					Oil
				</h2>
				<div class="divider-h">
					<span class="divider divider-half"></span>
				</div>

				<div class="row">
					<div class="col-sm-12">
						<a href="#" data-lightbox="img/.jpg" data-frame="dark-lb"><img src="img/.jpg" class="center-block landscape" alt="Sundown" /></a>
						<h4 class="mg-sm  text-center">
							Sundown (Sold)
						</h4>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- bloc-urbanscapes-oils END -->

<!-- bloc-urbanscapes-watercolours -->
<div class="bloc bgc-accent-bg l-bloc painting-text" id="bloc-urbanscapes-watercolours">
	<div class="container bloc-md">
		<div class="row">
			<div class="col-sm-12">
				<h2 class="text-center mg-md ">
					Watercolour
				</h2>
				<div class="divider-h">
					<span class="divider divider-half"></span>
				</div>
				<div class="row">
					<div class="col-sm-4">
						<a data-frame="dark-lb" data-lightbox="img/Cafes_Open.jpg" href="#">
							<img alt="Cafes... Open" class="center-block landscape" src="img/Cafes_Open.jpg"/>
						</a>
						<h4 class="mg-sm  text-center">Cafes... Open (Sold)</h4>
					</div>
					<div class="col-sm-4">
						<a href="#" data-lightbox="img/Portbou_Spain.jpg" data-frame="dark-lb"><img src="img/Portbou_Spain.jpg" class="center-block landscape" alt="Portbou, Spain" /></a>
						<h4 class=" text-center mg-sm">
							Portbou, Spain (Sold)
						</h4>
					</div>
					<div class="col-sm-4">
						<a data-frame="dark-lb" data-lightbox="img/Morning_View.jpg" href="#">
							<img class="center-block landscape" src="img/Morning_View.jpg" alt="Morning View"/>
						</a>
						<h4 class="mg-sm text-center">Morning View (Sold)</h4>
					</div>
				</div>
				<div class="row row-move-down">
					<div class="col-sm-12">
						<a data-frame="dark-lb" data-lightbox="img/Florence.jpg" href="#">
							<img alt="Florence (Sold)" class="center-block portrait" src="img/Florence.jpg"/>
						</a>
						<h4 class="mg-sm  text-center">Florence (Sold)</h4>
					</div>
				</div>
				<div class="row row-move-down">
					<div class="col-sm-3">
						<a href="#" data-lightbox="img/Ancient_Door_1.jpg" data-frame="dark-lb"><img src="img/Ancient_Door_1.jpg" class="center-block portrait" alt="Ancient Door 1" /></a>
						<h4 class=" text-center mg-sm">
							Ancient Door 1 (Sold)
						</h4>
					</div>
					<div class="col-sm-3">
						<a href="#" data-lightbox="img/Ancient_Door_2.jpg" data-frame="dark-lb"><img src="img/Ancient_Door_2.jpg" class="center-block portrait" alt="Ancient Door 2" /></a>
						<h4 class=" text-center mg-sm">
							Ancient Door 2 (Sold)
						</h4>
					</div>
					<div class="col-sm-3">
						<a href="#" data-lightbox="img/Ancient_Door_3.jpg" data-frame="dark-lb"><img src="img/Ancient_Door_3.jpg" class="center-block portrait" alt="Ancient Door 3" /></a>
						<h4 class=" text-center mg-sm">
							Ancient Door 3 (Sold)
						</h4>
					</div>
					<div class="col-sm-3">
						<a href="#" data-lightbox="img/Ancient_Door_4.jpg" data-frame="dark-lb"><img src="img/Ancient_Door_4.jpg" class="center-block portrait" alt="Ancient Door 4" /></a>
						<h4 class=" text-center mg-sm">
							Ancient Door 4 (Sold)
						</h4>
					</div>
				</div>
				<div class="row row-move-down">
					<div class="col-sm-3">
						<a href="#" data-lightbox="img/Ancient_Door_5.jpg" data-frame="dark-lb"><img src="img/Ancient_Door_5.jpg" class="center-block portrait" alt="Ancient Door 5" /></a>
						<h4 class=" text-center mg-sm">
							Ancient Door 5 (Sold)
						</h4>
					</div>
					<div class="col-sm-3">
						<a href="#" data-lightbox="img/Ancient_Door_6.jpg" data-frame="dark-lb"><img src="img/Ancient_Door_6.jpg" class="center-block portrait" alt="Ancient Door 6" /></a>
						<h4 class=" text-center mg-sm">
							Ancient Door 6 (Sold)
						</h4>
					</div>
					<div class="col-sm-3">
						<a href="#" data-lightbox="img/Ancient_Door_7.jpg" data-frame="dark-lb"><img src="img/Ancient_Door_7.jpg" class="center-block portrait" alt="Ancient Door 7" /></a>
						<h4 class=" text-center mg-sm">
							Ancient Door 7 (Sold)
						</h4>
					</div>
					<div class="col-sm-3">
						<a href="#" data-lightbox="img/Ancient_Door_8.jpg" data-frame="dark-lb"><img src="img/Ancient_Door_8.jpg" class="center-block portrait" alt="Ancient Door 8" /></a>
						<h4 class=" text-center mg-sm">
							Ancient Door 8 (Sold)
						</h4>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- bloc-urbanscapes-watercolours END -->

<?php include 'source/social_footer.php';?>

</div>
<!-- Main container END -->
    
<?php include 'source/scripts_footer.php';?>
</body>
    
<!-- Google Analytics -->
 
<!-- Google Analytics END -->

</html>
