<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>Lina Yachnin – Urbanscapes</title>
	<?php include 'source/meta_header.php';?>
	<meta property="og:title" content="Urbanscape paintings by Lina Yachnin — Canadian Oil & Watercolour Artist"/>
</head>
<body>
<!-- Main container -->
<div class="page-container">

<?php include 'source/navbar.php';?>

<!-- bloc-urbanscape-banner -->
<div class="bloc bg-Portbou bgc-white-2 l-bloc b-parallax bg-center banner" id="bloc-urbanscape-banner">
	<div class="container bloc-lg">
		<div class="row">
			<div class="col-sm-12">
				<h1 class="mg-md tc-white-2 mm-links">
					<strong>Urbanscapes</strong>
				</h1>
			</div>
		</div>
	</div>
</div>
<!-- bloc-urbanscape-banner END -->

<!-- bloc-urbanscapes-oils -->
<div class="bloc bgc-white-2 l-bloc painting-text" id="bloc-urbanscapes-oils">
	<div class="container bloc-md">
		<div class="row">
			<div class="col-sm-12">
				<h2 class="text-center mg-md ">
					Oil
				</h2>
				<div class="divider-h">
					<span class="divider divider-half"></span>
				</div>

				<div class="row">
					<div class="col-sm-4">
						<a href="#" data-lightbox="img/Night_Out.jpg" data-frame="dark-lb">
							<img src="img/Night_Out.jpg" class="center-block landscape" alt="Night Out" /></a>
						<h3 class=" text-center mg-sm">
							Night Out
						</h3>
						<p class="text-center">
							33" x 33"<br/>
							Oil on canvas<br />
							$1050
						</p>
					</div>
					<div class="col-sm-4">
						<a href="#" data-lightbox="img/Coffee_Time.jpg" data-frame="dark-lb">
							<img src="img/Coffee_Time.jpg" class="center-block landscape" alt="Coffee Time" /></a>
						<h3 class=" text-center mg-sm">
							Coffee Time
						</h3>
						<p class="text-center">
							33" x 33"<br/>
							Oil on canvas, framed<br />
							$1050
						</p>
					</div>
					<div class="col-sm-4">
						<a href="#" data-lightbox="img/Dining_Out.jpg" data-frame="dark-lb">
							<img src="img/Dining_Out.jpg" class="center-block landscape" alt="Dining Out" /></a>
						<h3 class=" text-center mg-sm">
							Dining Out
						</h3>
						<p class="text-center">
							27" x 40"<br/>
							Oil on gallery canvas, framed<br />
							$1250
						</p>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- bloc-urbanscapes-oils END -->

<!-- bloc-urbanscapes-watercolours -->
<div class="bloc bgc-gainsboro l-bloc painting-text" id="bloc-urbanscapes-watercolours">
	<div class="container bloc-md">
		<div class="row">
			<div class="col-sm-12">
				<h2 class="text-center mg-md ">
					Watercolour
				</h2>
				<div class="divider-h">
					<span class="divider divider-half"></span>
				</div>
				<div class="row">
					<div class="col-sm-6">
						<a href="#" data-lightbox="img/Evening_in_Spain.jpg" data-frame="dark-lb"><img src="img/Evening_in_Spain.jpg" class="center-block landscape" alt="Evening in Spain" /></a>
						<h3 class=" text-center mg-sm">
							Evening in Spain
						</h3>
						<p class=" text-center">
							24" x 30"<br/>
							Watercolour, framed<br />
							$875
						</p>
					</div>
					<div class="col-sm-6">
						<a href="#" data-lightbox="img/Irish_Corner.jpg" data-frame="dark-lb"><img src="img/Irish_Corner.jpg" class="center-block landscape" alt="Irish Corner" /></a>
						<h3 class=" text-center mg-sm">
							Irish Corner
						</h3>
						<p class=" text-center">
							24" x 30"<br/>
							Watercolour, framed<br />
							$875
						</p>
					</div>
				</div>
				<div class="row row-move-down">
					<div class="col-sm-6">
						<a href="#" data-lightbox="img/Evening_Out_II.jpg" data-frame="dark-lb"><img src="img/Evening_Out_II.jpg" class="center-block portrait" alt="Evening Out II" /></a>
						<h3 class=" text-center mg-sm">
							Evening Out II
						</h3>
						<p class=" text-center">
							24" x 30"<br/>
							Watercolour, framed<br />
							$875
						</p>
					</div>
					<div class="col-sm-6">
						<a data-frame="dark-lb" data-lightbox="img/Florence.jpg" href="#">
							<img alt="Florence (Sold)" class="center-block portrait" src="img/Florence.jpg"/>
						</a>
						<h3 class="mg-sm  text-center">Florence (Sold)</h3>
					</div>
				</div>
				<div class="row row-move-down">
					<div class="col-sm-4">
						<a data-frame="dark-lb" data-lightbox="img/Cafes_Open.jpg" href="#">
							<img alt="Cafes... Open" class="center-block landscape" src="img/Cafes_Open.jpg"/>
						</a>
						<h3 class="mg-sm  text-center">Cafes... Open (Sold)</h3>
					</div>
					<div class="col-sm-4">
						<a href="#" data-lightbox="img/Portbou_Spain.jpg" data-frame="dark-lb"><img src="img/Portbou_Spain.jpg" class="center-block landscape" alt="Portbou, Spain" /></a>
						<h3 class=" text-center mg-sm">
							Portbou, Spain (Sold)
						</h3>
					</div>
					<div class="col-sm-4">
						<a data-frame="dark-lb" data-lightbox="img/Morning_View.jpg" href="#">
							<img class="center-block landscape" src="img/Morning_View.jpg" alt="Morning View"/>
						</a>
						<h3 class="mg-sm text-center">Morning View (Sold)</h3>
					</div>
				</div>
				<div class="row row-move-down">
					<div class="col-sm-3">
						<a href="#" data-lightbox="img/Ancient_Door_1.jpg" data-frame="dark-lb"><img src="img/Ancient_Door_1.jpg" class="center-block portrait" alt="Ancient Door 1" /></a>
						<h3 class=" text-center mg-sm">
							Ancient Door 1 (Sold)
						</h3>
					</div>
					<div class="col-sm-3">
						<a href="#" data-lightbox="img/Ancient_Door_2.jpg" data-frame="dark-lb"><img src="img/Ancient_Door_2.jpg" class="center-block portrait" alt="Ancient Door 2" /></a>
						<h3 class=" text-center mg-sm">
							Ancient Door 2 (Sold)
						</h3>
					</div>
					<div class="col-sm-3">
						<a href="#" data-lightbox="img/Ancient_Door_3.jpg" data-frame="dark-lb"><img src="img/Ancient_Door_3.jpg" class="center-block portrait" alt="Ancient Door 3" /></a>
						<h3 class=" text-center mg-sm">
							Ancient Door 3 (Sold)
						</h3>
					</div>
					<div class="col-sm-3">
						<a href="#" data-lightbox="img/Ancient_Door_4.jpg" data-frame="dark-lb"><img src="img/Ancient_Door_4.jpg" class="center-block portrait" alt="Ancient Door 4" /></a>
						<h3 class=" text-center mg-sm">
							Ancient Door 4 (Sold)
						</h3>
					</div>
				</div>
				<div class="row row-move-down">
					<div class="col-sm-3">
						<a href="#" data-lightbox="img/Ancient_Door_5.jpg" data-frame="dark-lb"><img src="img/Ancient_Door_5.jpg" class="center-block portrait" alt="Ancient Door 5" /></a>
						<h3 class=" text-center mg-sm">
							Ancient Door 5 (Sold)
						</h3>
					</div>
					<div class="col-sm-3">
						<a href="#" data-lightbox="img/Ancient_Door_6.jpg" data-frame="dark-lb"><img src="img/Ancient_Door_6.jpg" class="center-block portrait" alt="Ancient Door 6" /></a>
						<h3 class=" text-center mg-sm">
							Ancient Door 6 (Sold)
						</h3>
					</div>
					<div class="col-sm-3">
						<a href="#" data-lightbox="img/Ancient_Door_7.jpg" data-frame="dark-lb"><img src="img/Ancient_Door_7.jpg" class="center-block portrait" alt="Ancient Door 7" /></a>
						<h3 class=" text-center mg-sm">
							Ancient Door 7 (Sold)
						</h3>
					</div>
					<div class="col-sm-3">
						<a href="#" data-lightbox="img/Ancient_Door_8.jpg" data-frame="dark-lb"><img src="img/Ancient_Door_8.jpg" class="center-block portrait" alt="Ancient Door 8" /></a>
						<h3 class=" text-center mg-sm">
							Ancient Door 8 (Sold)
						</h3>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- bloc-urbanscapes-watercolours END -->

<?php include 'source/social_footer.php';?>

</div>
<!-- Main container END -->

<?php include 'source/scripts_footer.php';?>
</body>

<!-- Google Analytics -->

<!-- Google Analytics END -->

</html>
