<div class="bloc bgc-<?php= $background ?> l-bloc painting-text" id="bloc-<?php= $curpage ?>-<?php= $heading ?>s">
	<div class="container bloc-md">
		<div class="row">
			<div class="col-sm-12">
				<h2 class="text-center mg-md ">
					<?php= ucwords($heading); ?>
				</h2>
				<div class="divider-h">
					<span class="divider divider-half"></span>
				</div>
				<!-- function call -->
			</div>
		</div>
	</div>
</div>

<div class="bloc bgc-gainsboro l-bloc painting-text" id="bloc-florals-oils">
	<div class="container bloc-md">
		<div class="row">
			<div class="col-sm-12">
				<h2 class="text-center mg-md ">
					Oil
				</h2>
				<div class="divider-h">
					<span class="divider divider-half"></span>
				</div>
				<!-- funtion call -->
			</div>
		</div>
	</div>
</div>